### ISSUE TITLE
Date function supports in PQL

### ISSUE THREAD

**Issue by shadowwalker2718** [apache/incubator-pinot#1051]
In MySQL, to query the data since the past 1 hour, I can use SQL like:

```
select count(*) as cnt from  log where date >= DATE_SUB(NOW(),INTERVAL 1 HOUR); 
```

How can I do the same in PQL? Will the date functions be added into PQL?

**Comment by mayankshriv** [comment]
Hi,
We don't have support for transforms/udf's on filter predicates currently,
but might be able to support it around Q2.
We do support transforms on group-by's, and will do the same for
aggregations next.

You can refer to the following design doc:
https://github.com/linkedin/pinot/wiki/Expressions-&-UDF-support

Thanks,
Mayank

**Comment by kishoreg** [comment]
@mayankshriv Can we support this now?

**Comment by fx19880617** [comment]
This is supported now, please refer to the datetime functions:

https://docs.pinot.apache.org/users/user-guide-query/supported-transformations#datetime-functions

**Comment by Jackie-Jiang** [comment]
Assume `date` is a `TIMESTAMP` type, you can do
```
select count(*) as cnt from log where date >= now() - fromEpochHours(1)
```
