### ISSUE TITLE
If I want to paging the pinot data, how can I do

### ISSUE THREAD

**Issue by debug529** [apache/incubator-pinot#111]
If I want to paging the pinot data, how can I do, maybe like this:
sql: select \* from baseballStats limit 10,20
pinot sql:?

**Comment by fx19880617** [comment]
same:
select * from baseballStats limit 10,20
10 is the offset, 20 is the number of rows.

**Comment by debug529** [comment]
but it don't work well,
I run the sql(select * from test order by time desc limit 10,20)in shell, 
it returned different results every time.

**Comment by fx19880617** [comment]
There is no global docId specified in Pinot.
If you want same results, you can try "select * from baseballStats order by [some column] limit 10,20".

**Comment by debug529** [comment]
@fx19880617  thanks! how about the paging which contains group by condition?
`/*Top 5 run scorers of the year 2000*/`
`select sum('runs') from baseballStats where yearID=2000 group by playerName top 5 limit 0`
it returned top 5 records, Bug if I want to get 5 to 10 records?
`select sum('runs') from baseballStats where yearID=2000 group by playerName limit 5,5`
but it default returned top 10, This is not correct

**Comment by kishoreg** [comment]
Pinot does not support pagination for aggregation/group
