### ISSUE TITLE
Possible null pointer dereference 

### ISSUE THREAD

**Issue by AppChecker** [apache/incubator-pinot#1436]
Hi.
Please look [this code fragment](https://github.com/linkedin/pinot/blob/b30514750e9b482abb383efcd5b8fdde33964969/thirdeye/thirdeye-pinot/src/test/java/com/linkedin/thirdeye/tools/FetchMetricDataAndExistingAnomaliesTool.java#L286):
` if (dimensions != null || !dimensions.isEmpty()) {`

if dimensions  is null -> (dimensions != null ) is false, so method isEmpty will be called, so NPE is happened.
Probably, it should be:
` if (dimensions != null && !dimensions.isEmpty()) {`

[Similar code](https://github.com/linkedin/pinot/blob/b30514750e9b482abb383efcd5b8fdde33964969/thirdeye/thirdeye-pinot/src/test/java/com/linkedin/thirdeye/tools/FetchMetricDataAndExistingAnomaliesTool.java#L289):
`    if (filterJson != null || !filterJson.isEmpty()) {`

This possible defect found by [AppChecker](https://npo-echelon.ru/en/solutions/appchecker.php)

**Comment by GavinDmello** [comment]
@kishoreg I think this issue should be closed as these type of checks aren't happening in the master branch anymore.

**Comment by shireennagdive** [comment]
@kishoreg Can we close this issue?

**Comment by babuneelam** [comment]
I looked for this code in master branch. But, both these code fragments don't exist in master branch:

    `if (dimensions != null || !dimensions.isEmpty()) {`

and 

    `if (filterJson != null || !filterJson.isEmpty()) {`


So, I believe this issue can be closed.
