### ISSUE TITLE
About coding style

### ISSUE THREAD

**Issue by tianyin** [apache/incubator-pinot#1635]
I checked out https://github.com/linkedin/pinot/wiki/Coding-guidelines and it states that 

"_Use standard LinkedIn code style in eclipse/idea to format the code. TODO: commit the checkstyle plugin into code._"

Could you let me know where can I find the LinkedIn code-style? 

I checked several LinkedIn projects and the code styles are all different (specified in their `CheckStyle` configurations), as follows,
https://github.com/linkedin/kafka-monitor/blob/master/checkstyle/checkstyle.xml
https://github.com/linkedin/shaky-android/blob/master/config/checkstyle/checkstyle.xml
https://github.com/linkedin/li-apache-kafka-clients/blob/master/config/checkstyle/checkstyle.xml
Take indentation as an example, `kafla-monitor` uses `2`, `shaky` uses `4` (the default), and `li-apache-kafka-clients` does not specify.

It seems to me that we're relying on `pinot-style.xml` which is only for Eclipse. 
I suspect that this style file is not always used.

I write a `CheckStyle` configuration based on this eclipse file and find a number of style violations.
For example, in `pinot-style.xml`, the indentation size is `2`, while you can find `5` spaces as an indentation (e.g., in Line 424 of `pinot-common/src/main/java/com/linkedin/pinot/common/metrics/AbstractMetrics.java`)

Well, I guess the `TODO: commit the checkstyle plugin into code` in the coding guidelines should be addressed...

Thanks!

**Comment by mcvsubbu** [comment]
https://pinot.readthedocs.io/en/latest/dev_env.html
