### ISSUE TITLE
Support LIKE in filtering?

### ISSUE THREAD

**Issue by fx19880617** [apache/incubator-pinot#207]
Kind of like the IN clause query, will need to scan dictionary to get all the matched dictionary id.

**Comment by jfim** [comment]
Is this only for prefix search (eg. LIKE 'potato%') or any search (eg. LIKE '%potato%').

**Comment by fx19880617** [comment]
if we want to support , we should do  any

**Comment by jfim** [comment]
Makes sense. Prefix search is doable with a combination greater than/equals and smaller than, but not any search. From checking the SQL92 spec, this is what we'd need to support:

- `%` 0-n characters (eg. `LIKE '%ato'` matches 'potato' and 'tomato')
- `_` exactly one character (eg. `LIKE '_ean'` matches 'Jean' and 'Dean')
- `ESCAPE` clause (eg. `LIKE '20!%' ESCAPE '!'` matches '20%' but not '20abcd')

The `ESCAPE` part would need some changes to the grammar, but nothing major. The best way would probably to convert the like clause to a regex on the server-side and find matching dictionary entry IDs, then process the query. This might be slow for large dictionaries.

**Comment by kishoreg** [comment]
@fx19880617 want to work on this? Looks straight forward. @jfim do we need to change grammar for this?

**Comment by kishoreg** [comment]
This is supported by Pinot. See https://github.com/apache/incubator-pinot/pull/1192
