### ISSUE TITLE
How is this different from Druid?

### ISSUE THREAD

**Issue by pdeva** [apache/incubator-pinot#3]
Some documentation/explanation regarding this would help greatly help people looking into or already using druid.

**Comment by kishoreg** [comment]
We are working on a wiki that details Pinot v/s other solutions. Will keep you posted.

**Comment by mistercrunch** [comment]
+1!

**Comment by izzizz** [comment]
+1! 
And how is it going?

**Comment by geo1211** [comment]
+1!
and how's that coming along =)

**Comment by rizwank** [comment]
Came up again during a demo at Strata+Hadoop Conf ; why not Druid?

**Comment by sskgit** [comment]
Any comparison with Druid?

**Comment by dhaval2025** [comment]
@fx19880617 ^^

**Comment by jaebinyo** [comment]
Just say it's similar with some enhancement and give credit to Druid community and move forward  :)

**Comment by niketh** [comment]
Any update? Want to figure out which way to go, Druid or Pinot

**Comment by raviarin** [comment]
Hi

Fundamentally Druid and Pinot are realtime distributed OLAP technologies. They both use columnar format for storage and a query processing engine on top. They differ in some integration aspects with other pieces of big data. For example in LinkedIn we run Pinot at a large scale (1000s of machines and 100s of tables). Pinot can directly consume data from Kafka and also from Hadoop. I cannot comment about Druid as I do not know their install base. There are a few features that might be missing in one and available in other and vice versa. Also, recently LinkedIn team has decided to make all their commits directly into open source. So any future development we do will land in open source immediately. There You will be getting the latest and greatest version all the time. From what I hear Uber is also using Pinot for their internal analytics. So your choice of technology will depend on the comfort levels. If I can find more details about DRUID installations I will be happy to share. That being said, I have a bias towards recommending Pinot as my team is actively working on it on a day to day basis. We will be happy to support your projects in the open source community.

**Comment by gowtham-sai** [comment]
Does Updates are possible in Pinot ?

**Comment by raviarin** [comment]
Pinot does not support direct update to rows right now. You can drop and update your entire segments if required. That being said, we are considering different options to provide update capabilities in the future.

**Comment by amalakar** [comment]
Hi @raviarin,

Thanks for your comment, as someone who is evaluating druid and pinot, I am trying to understand how they are different. Has there been any comparison made since your last comment? I noticed the [pinot-druid-benchmark](https://github.com/linkedin/pinot/tree/master/contrib/pinot-druid-benchmark) repo, are there any published benchmarks?

**Comment by kishoreg** [comment]
@Jackie-Jiang do we have any numbers that can be published externally?.

Arup, we had some numbers for the TPCH data but not sure if you can get to
any conclusion by looking at those numbers. To be honest, benchmarks will
favor the projects that publish them.

Take a look at the perf numbers published by Uber. They evaluated Pinot and
Druid on the same data set.
https://www.slideshare.net/XIANGFU3/pinot-near-realtime-analytics-uber

My suggestion is to try out both Pinot and Druid for your use case. It
should not be drastically different if you are using the standard inverted
index. But if you enable star tree index, depending on your queries, you
might see orders of magnitude difference.

Hope this helps.

**Comment by amalakar** [comment]
Kishore, thanks for your comment. Fair point regarding the benchmarks, and the slides are very helpful.

Is it fair in assuming that druid and pinot covers the same use cases. Apart from support for star tree index, are there any differences in philosophy or tradeoffs made in pinot compared to druid? 
I think what I am asking is apart from perf difference for my use cases, are there anything else you think would be worth considering in the evaluation?

**Comment by kishoreg** [comment]
Architecture is very similar - lambda. Pinot has a new component called
minion which will remove the need to have an offline component but this is
not ready for production. There is no SPOF in Pinot. Use of Helix for
cluster management is a big plus point for Pinot. It enables self
serve scenarios such as create table, rebalance tables, tag nodes, create
custom topology etc. Almost all the operations can be done dynamically
without needing to restart the servers. I haven't operated a Druid cluster,
so I can't really comment on the cluster management aspects of Druid, apart
from the fact that it needs an additional MySQL.

*Data format*

   - Druid mandates inverted index for all columns whereas it's optional in
   pinot and can be generated on demand when the query pattern changes. This
   can impact the segment size drastically.
   - Different encodings supported in Pinot - dictionary encoded, RLE for
   sorted columns, no dictionary snappy compression. These can be configured
   for each column.
   - Star tree index is definitely a big differentiator - this basically
   means you get Druid + Kylin in one system and you can choose the mode based
   on your qps and latency requirements.

*Query execution model is very different*

Pinot has a planning phase and execution phase and has the concept of
operator tree similar to how most DBs work. This means Pinot can do
optimizations on a per query basis and base it on the metadata of the
segment. For e.g if there are filters on two columns - one of them has
inverted index and the other does not. Irrespective of how the predicates
appear in the query - Pinot will reorder the predicate evaluation
appropriately. This is just an example, there are many other scenarios. In
practice, we have seen blindly having inverted index on columns performs
worse than having an inverted index on key columns and use scan based
filter for remaining columns.

In contrast, Druid has a constant plan - use an inverted index to get the
matching docs, scan the filtered docs and perform group by/aggregation.

*Features*

   - Most of the commonly used features are available in both Pinot and
   Druid. I think Druid does have support for Theta Sketches and Hyperloglog
   for distinct. Pinot as of now only supports HyperLogLog.
   - Group by along with top k result accuracy - by default we found Pinot
   group by results are more accurate than Druid. In both systems, there is
   some trimming done at node level (returning all results from each node will
   be inefficient). But in  Druid, we found that it trims the result at
   segment level as well. This might show up as Druid being a bit better for
   some queries in terms of latency but the results can be highly inaccurate.

*Documentation*

   - Druid definitely has better documentation than Pinot :-).

Hope this helps.
Note: I haven't really looked deep into Druid code base nor have I operated
a Druid cluster, so some of the info I have provided might be outdated. If
there are any Druid users reading this, please feel free to add your
comments.

thanks,
Kishore G

**Comment by mistercrunch** [comment]
@kishoreg I heard it may be possible to get non-probabilistic distinct counts on the segmentation key in Pinot, is that the case?

**Comment by kishoreg** [comment]
Yes, you can get the exact distinct count in Pinot.
https://www.linkedin.com/me/profile-views/ is powered by Pinot and computes
exact distinct count.

**Comment by mistercrunch** [comment]
Can you explain what that execution plan looks like? Is it achieved with an additional "partial shuffle" or by having nodes taking on all of the segments in their hash-space?

**Comment by kishoreg** [comment]
We support both modes but we don't capitalize on partitioned data as of now
for distinct operators. Let me explain -  We can ensure that segment with
same hash always gets assigned to the same node replica. The execution plan
is the same for both cases although I see your point that the query could
have been completely evaluated within the server node and broker could have
summed up the numbers from each server. This should be straightforward to
add such an aggregation operator to compute distinct from partitioned data.

**Comment by mistercrunch** [comment]
Let me clarify on my side, hoping to get a clearer understanding.

So say if my data is segmented by both `day` and `userid`, to facilitate both batch loading (allowing the drop/reload segments for a set of days) and userid to help with accurate distinct count.

Now if I want to get non-probabilistic DAUs out of this, what does the query (any SQL-hints?) and execution plan look like? Assuming I have say 32 buckets per day, does that mean each compute node will scan 32 segments and keep tabs of each userid, or will there be some sort of per-day shuffle phase?

**Comment by kishoreg** [comment]
Pinot doesn't support explicit hints. We set the partitioning scheme in the
table config e.g Data is partitioned on userId. During execution, if Pinot
sees a predicate on column userId such as userId=X, it automatically
filters out all other segments that don't belong to this partition. We
store the partition hash as part of each segment metadata. The broker
computes the subset of segments to process and routes the query to nodes
hosting these segments. These segments can be spread across the entire
cluster or few nodes (X) depending on the segment assignment strategy.Note
that X can 1, in which case entire gets executed on 1 node.

We don't do per day shuffle yet. Feel free to start another thread to go
over this in detail.




On Thu, Nov 16, 2017 at 9:31 AM, Maxime Beauchemin <notifications@github.com

**Comment by leventov** [comment]
[This blog post comparing ClickHouse, Druid and Pinot](https://medium.com/@leventov/comparison-of-the-open-source-olap-systems-for-big-data-clickhouse-druid-and-pinot-8e042a5ed1c7) could be interesting for people who read this issue.

**Comment by mamtasharma311** [comment]
Similarities between Apache Druid & Apache Pinot
[https://www.decipherzone.com/blog-detail/druid-vs-pinot](https://www.decipherzone.com/blog-detail/druid-vs-pinot)
Apache Druid and Apache Pinot are both fundamentally similar because they store data and process queries on the same nodes, deviating from the decoupled architecture of BigQuery. Druid and Pinot both have their data storing format with indexes, are tightly coupled with their query processing engines, and unsupportiveness of large data volumes between nodes, so the queries run faster in both than Big Data processing systems like Presto, Hive, Spark, Kudu and Parquet.
