### ISSUE TITLE
Support reading parquet file

### ISSUE THREAD

**Issue by shouhm** [apache/incubator-pinot#308]
Is it possible to support reading parquet format file(instead of json + schema) made from segment generation? The purpose to do this is automatically load some data transform without providing a user specified schema.

**Comment by kishoreg** [comment]
We don't have the support to read parquet format yet. Should be trivial to
add one.

**Comment by VicoWu** [comment]
@kishoreg @shouhm  
Columnar format like `Parquet/ORC` is now widely used, instead, row-oriented format like `JSON/Text/AVRO` is rarely used now. So, do you think it is valuable to do so?  I know that for Druid, it could support Parquet/ORC by its extension feature(http://druid.io/docs/latest/development/extensions.html). 
For other Realtime OLAP like `kudu + impala` , it also support `Parquet/ORC`.
So, could any one answer below questions:
1. Is it feasible to do so? 
2. Is it valuable to do so?

**Comment by kishoreg** [comment]
Yes, it is feasible and valuable to do that. 

See the current readers here. https://github.com/apache/incubator-pinot/blob/master/pinot-core/src/main/java/org/apache/pinot/core/data/readers

Adding ORC and Parquet Readers is easy. Once the readers are implemented, add them to the RecordReaderFactory. 

https://github.com/apache/incubator-pinot/blob/master/pinot-core/src/main/java/org/apache/pinot/core/data/readers/RecordReaderFactory.java

Want to give it a shot?

**Comment by VicoWu** [comment]
@kishoreg Great thanks for your reply. It really sounds great. 
I will have a deep insight on pinot code and implement and ping you if I have any update.

**Comment by BACtaki** [comment]
@VicoWu do you have any updates? @kishoreg I would like to take a stab at this if the task is still available

**Comment by fx19880617** [comment]
@BACtaki  Parquet is already supported as a file input format plugin:

https://github.com/apache/incubator-pinot/tree/master/pinot-plugins/pinot-input-format/pinot-parquet
