### ISSUE TITLE
push data

### ISSUE THREAD

**Issue by sunny800629** [apache/incubator-pinot#3315]
Can Pinot push data through HTTP API?

**Comment by mcvsubbu** [comment]
I suppose the question is whether data can be pushed to Pinot via HTTP? If so, the answer is yes. 

Pinot supports a segment POST via HTTP. The curl usage of the segment upload would be:

`curl -X POST -F segmentName=@segmentFile controllerHost:controllerPort/segments`

Hope this answers your question
