### ISSUE TITLE
Fatal error during dictionary creation

### ISSUE THREAD

**Issue by fx19880617** [apache/incubator-pinot#3355]
We encounter this issue with current master code. Our previous build is in April which doesn't have this issue.
Seems like it's related to dictionary creation for large string columns.

Some ref from hs_err_pid40175.log file.
> Stack: [0x00007fc5984f5000,0x00007fc5985f6000],  sp=0x00007fc5985f44e0,  free space=1021k
> Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
> J 14055 C2 com.linkedin.pinot.core.io.util.FixedByteValueReaderWriter.writeUnpaddedString(II[B)V (84 bytes) @ 0x00007fd36b6a1208 [0x00007fd36b6a0ee0+0x328]
> J 14068% C2 com.linkedin.pinot.core.segment.creator.impl.SegmentDictionaryCreator.build()V (2352 bytes) @ 0x00007fd36b6e2364 [0x00007fd36b6e21c0+0x1a4]
> j  com.linkedin.pinot.core.segment.creator.impl.SegmentColumnarIndexCreator.init(Lcom/linkedin/pinot/core/indexsegment/generator/SegmentGeneratorConfig;Lcom/linkedin/pinot/core/segment/creator/SegmentIndexCreationInfo;Ljava/util/Map;Lcom/linkedin/pinot/common/data/Schema;Ljava/io/File;)V+344
> j  com.linkedin.pinot.core.segment.creator.impl.SegmentIndexCreationDriverImpl.buildRaw()V+65
> j  com.linkedin.pinot.core.segment.creator.impl.SegmentIndexCreationDriverImpl.build()V+15
> j  com.linkedin.pinot.core.realtime.converter.RealtimeSegmentConverter.build(Lcom/linkedin/pinot/core/indexsegment/generator/SegmentVersion;Lcom/linkedin/pinot/common/metrics/ServerMetrics;)V+367
> J 13651% C1 com.linkedin.pinot.core.data.manager.realtime.HLRealtimeSegmentDataManager$2.run()V (1199 bytes) @ 0x00007fd36b4cb81c [0x00007fd36b4c74e0+0x433c]
> j  java.lang.Thread.run()V+11
> v  ~StubRoutines::call_stub
> V  [libjvm.so+0x68c453]
> V  [libjvm.so+0x689c24]
> V  [libjvm.so+0x68a1c9]
> V  [libjvm.so+0x6cc52d]
> V  [libjvm.so+0xa3fc12]
> V  [libjvm.so+0x8e3b62]
> C  [libpthread.so.0+0x8064]  start_thread+0xc4

**Comment by mcvsubbu** [comment]
Interesting, we hit it yesterday as well.

The long term fix for this is to have a dictionary that does not pad byes, but in the short term we should limit the number of characters in the string dictionary value and truncate it. The value can be configurable in stream config (not sure if we should make it configurable on a per column basis) but the default can be .... say 1024 chars? Or even 512 chars?

**Comment by mcvsubbu** [comment]
In our case it was not production table, so we got the table running by updating the zk segment metadata to set the start offset to the last consumed offset for the segment (essentially skipping that particular segment) and restarting the servers.

**Comment by fx19880617** [comment]
Sounds good, I think per table based config should be good enough. 
We have many tables on same tenant, so it's hard to find which table really hit this issue.

**Comment by fx19880617** [comment]
it's HLC, just our log is pretty messy and it's crash during bootstrap, which many tables are persisting also.

I think it's good to put at schema however it may impact existing users if they just slightly exceeds the new threshold.

**Comment by mcvsubbu** [comment]
If we allow users to set the limit in the schema, (bit have the default at, say 512 chars) we should be ok, right? Yes. existing users who exceed 512 chars (_and_ use the string in the query) may see a problem. They will need to update their schema to a value that they can live with. Of course, the higher this value, the lower the cardinality needs to be so that the dictionary does not explode. This is until we have variable length dictionary implemented.

@fx19880617  would you be able to code this up? thanks

**Comment by fx19880617** [comment]
Had an offline discussion with @Jackie-Jiang about where to put this: dictionary persistence/message decoder. I still have some data consistency concern/backward-compatibility for existing use cases, e.g. how to figure out the max entry length for each column for every table.

Meanwhile I'm playing with non-dictionary encoding, but also seeing other issue https://github.com/linkedin/pinot/issues/3373.
