### ISSUE TITLE
Deep Storage Support for Realtime

### ISSUE THREAD

**Issue by jenniferdai** [apache/incubator-pinot#3420]
We want to enable realtime support in deep storage by integrating the code with PinotFS APIs. We currently have two commit protocols for realtime, split and single-API commit. For this project, we will use the split commit protocol where we separate commit start, upload, and commit end into separate steps.

To enable split commit, you will need to set a config on the controller and server. 
On the controller side, you will need to set "controller.enable.split.commit" to true.
On the server side, you will need to set "pinot.server.instance.enable.split.commit" to true.

### Controller Side
LLCSegmentCompletionHandlers has the APIs for realtime segment upload. For split commit, we split the steps in the APIs into the following endpoints (segmentCommitStart, segmentUpload, segmentCommitEnd) while for single-API realtime segment commit, we call segmentCommit. Right now, we do not support deep storage because all the filesystem APIs we call assume that we are using local storage or NFS. To make this compatible, we need to introduce the PinotFS abstraction within realtime uploads. 

**segmentCommitStart**
For deep storage, no changes need to be made to segmentCommitStart.

**segmentUpload**
During this step, we create a temporary file with the segment we wanted to commit after the first step and write to that. To make this compatible with deep storage, we will need to write this file to deep storage instead of local controller storage. 

**segmentCommitEnd**
During this step, we move the temporary segment file once more and commit the metadata.
- We do a segment move here with our temp file to the final segment location, which we will need to use PinotFS APIs for.
-Then, we commit the segment metadata. In the first pass, we will still need to download the segment from deep storage or send the entire segment with .tar.gz in order to to get the segment metadata. In either case, we will need to change the way we construct the download url to make this closer to URI upload. 

We can combine the realtime and offline segment uploads so that both of them can use URI upload by going through the same code path. In the realtime case, segmentCommitEnd is actually the equivalent to segment upload. See discussion at the end for optimization where we will not need to download the file on the controller side (segment metadata only upload). 

Alternatively, we can simply use the .tar.gz approach and send the entire segment once it is completed by the server to the controller through multipart upload. However, not only will this be more difficult for migration later on, but we will still need to add the download uri. Best will be to move to the new endpoint and clearly reject wrong combinations of parameters in the code. Regardless, it will be through different segment endpoints since we will keep the call to segmentCommitEnd for realtime, just unify the code path.

### Server Side

In ServerSegmentCompletionProtocolHandler, we create the requests that are sent to the controller.

**SegmentCommitStart**
For segmentCommitStart, no changes need to be made.

**SegmentCommitUpload**
For segmentCommitUpload, we will need to construct an appropriate URI depending on whether we want the segment to go, to deep storage or to local storage on the controller. In order to do this, we will create a new configuration on the server side that allows us to pass in a parameter for final data dir, much like the one we have on the controller. Depending on the scheme attached to the data dir uri, we will decide whether the segment will go to deep storage or local storage on the controller. 

On the controller side, the config is private static final String DATA_DIR = "controller.data.dir";

We already have a data.dir config on the server side for the local place we want segments to go. Now we want to add the same config. We will call it server.persisted.data.dir and configure that inside HelixServerStarter upon server start. In the case it isn't configured, we will default to the local filesystem implementation.

**SegmentCommitEnd**
For segmentCommitEnd, no changes need to be made.

### Testing
I have a SplitCommitIntegrationTest that we can test with. Ideally, I would also like to set up a hadoop cluster and start to have a set of integration tests with deep storage support there, for retention, realtime, etc.

**Other discussions that I will put in another issue**
How to support multiple schemes for the same protocol (eg: different HDFS clusters)

Adding a segmentUploader to create different upload handlers for filesystem uploads or uploads where we want the uri to be http, so we decouple protocol from scheme.

Adding a file verification method to PinotFS - eg: on HDFS, files have MD5 checksums.

Metadata Upload (prereq = multiple schemes for same protocol)

@fx19880617 @chenboat

**Comment by fx19880617** [comment]
@jamesyfshao ^^

**Comment by jenniferdai** [comment]
@chenboat do you have any concerns/questions about this? Would love any feedback or to help in any way.

**Comment by fx19880617** [comment]
Overall looks good to me! 
For testing part, will SplitCommitIntegrationTest have kafka/controller/server setup and test data ingestion?
Do you have the detailed plan and task splits for development so @chenboat  could also help? Maybe we could split by controller & server.
My suggestion is that we could refactor all the localFS operations to using PinotFS APIs. Then try out new implementations like HDFS.

**Comment by chenboat** [comment]
@jenniferdai , thanks for the detailed design. A few questions to confirm about the segment upload.
> On the controller side,  segmentUpload()...
> During this step, we create a temporary file with the segment we wanted to commit after the first step and write to that ...

"We" refers to the controller? If so, the controller will create and write the file to either deep storage or local file system. Is there a way to let the server upload the segment to the deep storage directly and pass only metadata to the controller for commit? Your server side segmentCommitUpload() design seems to allow "either the segment will go to deep storage or local storage on the controller".

**Comment by chenboat** [comment]
> -Then, we commit the segment metadata. In the first pass, we will still need to download the segment from deep storage or send the entire segment with .tar.gz in order to to get the segment metadata.

Why do we need to download the segment again to get segment metadata info? Which kind of info we can get from a download? Can we get them the query parameters of segCommitEnd request?

**Comment by fx19880617** [comment]
> > -Then, we commit the segment metadata. In the first pass, we will still need to download the segment from deep storage or send the entire segment with .tar.gz in order to to get the segment metadata.
> 
> Why do we need to download the segment again to get segment metadata info? Which kind of info we can get from a download? Can we get them the query parameters of segCommitEnd request?

I think this is the first phase which we follow the same steps as offline segment push to download segment from remote storage in controller and load segment metadata from it.

Eventually we should be able to get rid of controller downloading segments and only push segment metadata.

**Comment by chenboat** [comment]
A [meeting note](https://docs.google.com/document/d/16ny6mVwxgCBOVsSuXQmfYGtaXbONykURWQWZYuC7pUQ/edit#heading=h.11ytvbgvo26h) summarizing our discussion on Wednesday. Feel free to edit or comments. 

@jenniferdai @fx19880617 @jamesyfshao

**Comment by chenboat** [comment]
A proposal to remove the segment data downloading by Controller for metadata extraction is added by @npawar  and @mcvsubbu.
[https://cwiki.apache.org/confluence/display/PINOT/Segment+Completion+Protocol+enhancements+for+Deep+Store+support](url)

**Comment by chenboat** [comment]
Close this issue now as this feature is completed in the head of Pinot now and tested in Uber. Thanks @jenniferdai @fx19880617 @npawar @mcvsubbu @icefury71

**Comment by chenboat** [comment]
@jenniferdai can you close this issue since it is done by now?
