### ISSUE TITLE
Who knows what these two fields mean? In the table segmentConfig '

### ISSUE THREAD

**Issue by ly923976094** [apache/incubator-pinot#3460]
segmentPushFrequency：hourly, daily, weekly
segmentPushType：APPEND or REFRESH

**Comment by jackjlli** [comment]
@ly923976094 In Pinot, `segment push` is pretty much the same as `segment upload`.  
`segmentPushFrequency` is the frequency of uploading new created / updated segments to Pinot cluster.
`APPEND` use case is that the segment to be uploaded is brand new and it's just added to the previous set of segments. Thus the number of segments for that table in the cluster will be increased.
`REFRESH` use case is that the segment to be uploaded is updated from a previous segment and will replace the previous segment in the pinot cluster. The number of segments for that table remains the same.

**Comment by mcvsubbu** [comment]
To add to what @jackjlli  mentioned, think of REFRESH use case as one in which all data is refreshed by re-loading the entire data (i.e. all segments are replaced). In contrast. APPEND use cases add a segment (or a few) each day (or hour) with new data while old data is retained out.

HOURLY, DAILY, etc. are values of segment PushFrequency. It is used in the ValidationManager to detect gaps in existing segments and raise alerts. It is also used to name the segments correctly while generating Pinot segments.

Hope this helps.

**Comment by ly923976094** [comment]
Thank you @jackjlli @mcvsubbu, so is segmentPushFrequency only for offline data ( for example hadoop, local)? What should the value be for real-time data ( for example kafka)? @mcvsubbu, You mentioned that It is used in the ValidationManager to detect gaps in existing segments and raise alerts. Where is this alarm configured

**Comment by ly923976094** [comment]
> To add to what @jackjlli mentioned, think of REFRESH use case as one in which data is refreshed by re-loading the entire data (i.e. all segments are replaced). In contrast. APPEND use cases add a segment (or a few) each day (or hour) with new data while old data is retained out.
> 
> HOURLY, DAILY, etc. are values of segment PushFrequency. It is used in the ValidationManager to detect gaps in existing segments and raise alerts. It is also used to name the segments correctly while generating Pinot segments.
> 
> Hope this helps.
Thank you @jackjlli @mcvsubbu, so is segmentPushFrequency only for offline data ( for example hadoop, local)? What should the value be for real-time data ( for example kafka)? @mcvsubbu, You mentioned that It is used in the ValidationManager to detect gaps in existing segments and raise alerts. Where is this alarm configured

**Comment by jackjlli** [comment]
@ly923976094 The segmentPushFrequency is also used for realtime data as well. The value would be the same as the ones you mentioned, like `"segmentPushFrequency": "daily"`.

So ValidationManager is run at the background when Pinot controller is up and running. It's configured in pinot controller config: `controller.validation.frequencyInSeconds`.  Basically it gets the frequency of segment push defined in the table config and then searches for any gaps between data. E.g. if the frequency is set to `daily`, and the validation manager found out there's no data for 11/11, then validation manager would log the message saying `"Table: blabla has segments with invalid interval: blabla1-blabla2`, and emit any metric if possible. You can check the code in `ValidationManager.java` for more details on how Validation manager works.

**Comment by ly923976094** [comment]
> @ly923976094 The segmentPushFrequency is also used for realtime data as well. The value would be the same as the ones you mentioned, like `"segmentPushFrequency": "daily"`.
> 
> So ValidationManager is run at the background when Pinot controller is up and running. It's configured in pinot controller config: `controller.validation.frequencyInSeconds`. Basically it gets the frequency of segment push defined in the table config and then searches for any gaps between data. E.g. if the frequency is set to `daily`, and the validation manager found out there's no data for 11/11, then validation manager would log the message saying `"Table: blabla has segments with invalid interval: blabla1-blabla2`, and emit any metric if possible. You can check the code in `ValidationManager.java` for more details on how Validation manager works.

@jackjlli In my practice, kafka real-time data was first loaded into memory, and when I turned off the stored server, the data disappeared. When did the data in memory flush to disk? It has something to do with segmentPushFrequency

**Comment by ly923976094** [comment]
@jackjlli My understanding is that segmentPushFrequency is ValidationManager monitoring daily or hourly monitoring of whether you are pushing data into a pinot cluster
