### ISSUE TITLE
Who knows what it means to consume kafka data in real time in table config

### ISSUE THREAD

**Issue by ly923976094** [apache/incubator-pinot#3486]
replicasPerPartition（The documentation provided is not quite clear, is it how many consumers (server) consumption kafka partition means） ，stream.kafka.consumer.prop.auto.offset.reset and  realtime.segment.flush.threshold.size

{
    "tableName":"test",
    "segmentsConfig":{
        "retentionTimeUnit":"DAYS",
        "retentionTimeValue":"3",
        "segmentPushFrequency":"daily",
        "segmentPushType":"APPEND",
        "replication":"2",
        "schemaName":"test",
        "timeColumnName":"timestamp",
        "timeType":"MILLISECONDS",
        "segmentAssignmentStrategy":"BalanceNumSegmentAssignmentStrategy",
        "replicasPerPartition":"2"
    },
    "tableIndexConfig":{
        "loadMode":"HEAP",
        "lazyLoad":"false",
        "streamConfigs":{
            "streamType":"kafka",
            "stream.kafka.consumer.type":"simple",
            "stream.kafka.topic.name":"pinot_test",
            "stream.kafka.decoder.class.name":"com.linkedin.pinot.core.realtime.impl.kafka.KafkaJSONMessageDecoder",
            "stream.kafka.broker.list":"localhost:9092",
            "realtime.segment.flush.threshold.time":"3600000",
            "realtime.segment.flush.threshold.size":"100",
            "stream.kafka.consumer.prop.auto.offset.reset":"smallest"
        }
    },
    "tableType":"REALTIME",
    "tenants":{
        "broker":"brokerTest",
        "server":"serverTest"
    },
    "metadata":{

    }
}

**Comment by fx19880617** [comment]
replicasPerPartition is the # replication of this table(Ensure the #servers in server tenant is larger than #replicas) when you create the table.

**Comment by ly923976094** [comment]
> replicasPerPartition is the # replication of this table(Ensure the #servers in server tenant is larger than #replicas) when you create the table.

What's the difference between this and the replication field.

**Comment by fx19880617** [comment]
`replicasPerPartition` is only used with Kafka simple consumer ("stream.kafka.consumer.type":"simple"). In this case, it's same as `replication`.

**Comment by ly923976094** [comment]
> `replicasPerPartition` is only used with Kafka simple consumer ("stream.kafka.consumer.type":"simple"). In this case, it's same as `replication`.

I understand. Thank you @fx19880617
