### ISSUE TITLE
Realtime Ingestion stopped when expanding a tenant with High Level Consumer

### ISSUE THREAD

**Issue by icefury71** [apache/incubator-pinot#3538]
Adding more servers to an existing tenant causes realtime ingestion to stop in case of High Level Consumers, for new segments in all tables in that tenant. We see this exception in the server log:

`Caught exception while processing resource <table-name>. Skipping`. 

The root cause seems to be inside `PinotRealtimeSegmentManager.java` which fails to get instance Zk metadata for the new instance.

**Comment by mcvsubbu** [comment]
Can you please provide the complete exception stack on the server, error message with exception stack (if any) on the controller, and the git hash of the version of pinot you are using?

Also, have you added the instance config  in zk for the new instance added? Unfortunately, this is a manual zk edit. IIRC you need to add a new instance config for each realtime instance you configure, and wait for it to catch up on the topic before turning it on for queries to that server.

We encourage moving to LLC (if possible) -- administration is a lot easier.

**Comment by fx19880617** [comment]
I think the exception stack is somehow swallow. 
My observation is, when we add new servers into the realtime tenant. The znode under path: /PROPERTYSTORE/CONFIGS/INSTANCE/{hostname} is not existed, which throws the exception. 
Need to further check the scenario that zNode is existed but without the kafka group/partition mapping set there.

**Comment by icefury71** [comment]
Based on Xiang's comments - looks like this is not supported in HLC. Closing issue.
