### ISSUE TITLE
PQL Support for generalized expressions in selection and aggregation

### ISSUE THREAD

**Issue by agrawaldevesh** [apache/incubator-pinot#3539]
The context is that I am trying to enable more general purpose analytics atop my Pinot tables. The idea being that users shouldn't have to precisely log the exact expression they are interested in. I am trying to hook up Apache Superset with Pinot. 

So I would like support for such features:
1. Single column simple expressions: "select max(2 * bytesRead) from foo" or "select 2*max(bytesRead) from foo"
2. Multi column simple expressions: "select max(bytesRead/bytesWritten) from foo" (Would this be hard to implement ?)
3. More and more support for SQL constructs like IF, CASE etc. 

Do you think these features would be straight forward to implement or would they require some architectural changes/refactoring before we can have them ? Are there efforts in the community that relate to this ? Also, what's the overall plan/roadmap about such SQL-ness ? 

Thanks

**Comment by Jackie-Jiang** [comment]
The first 2 cases are already supported in Pinot.
1. SELECT MAX(MULT(bytesRead, 2)) FROM foo
2. SELECT MAX(DIV(bytesRead, bytesWritten)) FROM foo

We have support for function: ADD, SUB, MULT, DIV in aggregation. Currently no support for selection yet (they are not that useful though because you can perform the operation on client side). Feel free to try them out.

**Comment by agrawaldevesh** [comment]
Doing expressions on the client side (in the select statement) can be done on the client but it is essentially an involved operation: 

Consider a contrived query like this: Select mul(foo, 2), div(foo, bar) from Table where mul(baz, 4) = 10. 

If this query is generated in an adhoc manner, the client would have to have support for parsing this query and figuring out that the foo, bar need to multiplied like so and that baz has to be ignored. That's a lot to ask from a client and it is something that would be easier to implement in the database itself. 

Can you help me understand how much work would it be to implement such features ? I am happy implementing if they won't require a lot of architectural changes :-)

**Comment by Jackie-Jiang** [comment]
I tried to implement it, but found the change is not trivial (don't remember the details). Selection should not be very hard to support, and does not requires architectural changes. But filter support would be hard, and the performance could be very bad because no index can be applied.

**Comment by sunny209868** [comment]
> Doing expressions on the client side (in the select statement) can be done on the client but it is essentially an involved operation:
> 
> Consider a contrived query like this: Select mul(foo, 2), div(foo, bar) from Table where mul(baz, 4) = 10.
> 
> If this query is generated in an adhoc manner, the client would have to have support for parsing this query and figuring out that the foo, bar need to multiplied like so and that baz has to be ignored. That's a lot to ask from a client and it is something that would be easier to implement in the database itself.
> 
> Can you help me understand how much work would it be to implement such features ? I am happy implementing if they won't require a lot of architectural changes :-)

hello，@agrawaldevesh Superset already supports pinot, but how do I graph it? My time field is in milliseconds
sqllab
![image](https://user-images.githubusercontent.com/20608540/57695367-aa814200-7680-11e9-9048-a7e94da9c5ae.png)

charts 
The data has been queried, but superset does not display it
![image](https://user-images.githubusercontent.com/20608540/57695478-f92edc00-7680-11e9-919d-dd15ec0434d8.png)

**Comment by Jackie-Jiang** [comment]
All the asked features are supported now with SQL query

**Comment by hpvd** [comment]
its an old issue... but I found this approach for this topic of convergent SQL and PQL very interesting:
Towards a Converged Relational-Graph Optimization Framework https://arxiv.org/html/2408.13480v1
