### ISSUE TITLE
Unable to create segments: Exception in thread "main" java.lang.ClassNotFoundException: SegmentCreation.class

### ISSUE THREAD

**Issue by reviliant** [apache/incubator-pinot#3635]
"hadoop jar pinot-hadoop-0.016.jar SegmentCreation job.properties" is not working

I found a class SegmentCreationJob.class but it does not have main method

**Comment by ly923976094** [comment]
> "hadoop jar pinot-hadoop-0.016.jar SegmentCreation job.properties" is not working
> 
> I found a class SegmentCreationJob.class but it does not have main method

You can jar it in sentences
mvn  license:format 
mvn clean install -DskipTests -Pbuild-shaded-jar，
Then use pinot-hadoop/target/pinot-hadoop-0.016-shaded.jar
Finally, use the following statement
/usr/local/hadoop-2.8.2/bin/hadoop pinot-hadoop-0.016-shaded.jar SegmentCreation job.properties
/usr/local/hadoop-2.8.2/bin/hadoop jar lib/pinot-hadoop-0.016-shaded.jar SegmentTarPush job.properties
I wonder if I can solve your problem

**Comment by jenniferdai** [comment]
Does this work for you? https://github.com/apache/incubator-pinot/wiki/Offline-Index-Creation

You can try generating the shaded jar.

**Comment by wqi-zz** [comment]
Hello, can confirm from here compiling the shaded jar resolved the error for me. Thanks!
