### ISSUE TITLE
Increase frequency of ValidationManager to fix realtime consumption stopped issues faster than 1 hour

### ISSUE THREAD

**Issue by npawar** [apache/incubator-pinot#3642]
Currently the ValidationManager runs periodically, every 60 minutes. During a run, the ValidationManager checks for any partitions of realtime tables that are stopped consuming, and fixes the ideal state and segment metadata so that the consumption can resume.
Running the ValidationManager every 60 minutes would mean that we can only guarantee freshness of data upto 60 minutes ago. We also have a check "isTooSoonToCorrect". This check skips correcting any segments that were updated within the last 10 minutes. This effectively pushes our freshness to 1h 10m.

This delay of 1h 10m is not acceptable to certain use cases. 

One way to solve this is:
1) Make the Validation Manager run sooner than every 60 minutes (10 minutes?) We have to check if doing so would add additional load on zk. In particular we need to watch for operations that would read all segment metadata for all tables. We should also ensure that we do only the realtime correction part frequently, and not the other things that ValidationManager is responsible for (eg. checking offline segments for gaps in time)

**Comment by mcvsubbu** [comment]
The validation manager run frequency is configurable

**Comment by kishoreg** [comment]
Should we break up the tasks in the validation manager into individual tasks and have different frequency for each task. Didn't we write a framework to manage all periodic tasks?

**Comment by npawar** [comment]
Looks okay to reduce frequency once https://github.com/apache/incubator-pinot/pull/3633 is done

**Comment by npawar** [comment]
@kishoreg found out that there is already a flag in ValidationManager periodic task which makes some tasks run 6 hourly, and only the realtime validation run hourly. Increasing the frequency should be safe in this case.
But I agree, those should be split out, instead of having different frequencies within a periodic task

**Comment by mcvsubbu** [comment]
@kishoreg we discussed that as well, but right now, the validation on offline tables is defaulted to a much lower frequency than realtime consumptin validation (but both are still in validation manager).

Yes, it does make sense to split the two managers and run one of them more frequenty. Perhaps we can do that when we distribute the controller load.

**Comment by npawar** [comment]
The tasks have been split out. The controller config `controller.realtime.segment.validation.frequencyInSeconds` can be used to change frequency of realtime validation
