### ISSUE TITLE
thirdeye with druid

### ISSUE THREAD

**Issue by feng-tao** [apache/incubator-pinot#3673]
Is it possible to integrate thirdeye with druid?

**Comment by kishoreg** [comment]
Not as of now. You will have to write an adapter. We are planning to add
support for data sources that support JDBC such as MySQL and Presto.

**Comment by feng-tao** [comment]
thanks @kishoreg .

**Comment by ibotheperfect** [comment]
Druid also supports jdbc now. 
https://druid.apache.org/docs/latest/querying/sql.html#jdbc
