### ISSUE TITLE
DefaultTenant and CustomTenant machines have different roles

### ISSUE THREAD

**Issue by ly923976094** [apache/incubator-pinot#3820]
DefaultTenant server can tag offline and in real time

serverInfoList:
- name: Server_172.31.68.28_8098
  state: ONLINE
  tags: [DefaultTenant_OFFLINE, DefaultTenant_REALTIME]
- name: Server_172.31.189.68_8098
  state: ONLINE
  tags: [DefaultTenant_OFFLINE, DefaultTenant_REALTIME]
tableInfoList: []

The CustomTenant server can only tag in real-time or offline. Is there a way for CustomTenant servers to tag in both? (like DefaultTenant server can tag offline and in real time) 

serverInfoList:
- name: Server_10.85.126.113_8098
state: ONLINE
tags: [serverOne_OFFLINE]
- name: Server_10.85.126.94_8098
state: ONLINE
tags: [serverOne_REALTIME]

**Comment by mcvsubbu** [comment]
you can use helix-admin commands to add the additional tags as needed. Download helix from  https://helix.apache.org/

**Comment by ly923976094** [comment]
> you can use helix-admin commands to add the additional tags as needed. Download helix from https://helix.apache.org/

yes，thank you @mcvsubbu ，Added successfully
 bin/helix-admin.sh -zkSvr '10.210.136.61:2181,10.210.136.62:2181,10.210.136.64:2181' -addInstanceTag dip-summon-pinot-cluster Server_10.55.22.107_8098 serverOne_REALTIME
