### ISSUE TITLE
The segment status is ERROR

### ISSUE THREAD

**Issue by ly923976094** [apache/incubator-pinot#3904]
If I upload the segment status offline to pinot, it is ERROR. What is the reason？
![image](https://user-images.githubusercontent.com/20608540/53734769-f2852b00-3ebf-11e9-89d4-c4d10b9b4928.png)

**Comment by mcvsubbu** [comment]
Have you looked at what the servers log for the segment?

**Comment by ly923976094** [comment]
I haven't read the servers log yet, but the feedback from the uploaded client is that the data upload was successful
