### ISSUE TITLE
Pinot delete data

### ISSUE THREAD

**Issue by ly923976094** [apache/incubator-pinot#3933]
Does pinot have a way to delete data based on the time range of the time field?

**Comment by mcvsubbu** [comment]
No, Pinot does not have such a feature. Note that Pinot data is immutable except on a per-segment basis. Older segments are deleted by time if you set a retention period, as long as the  most recent row in the segment is still older than the retention time.

**Comment by PeterCorless** [comment]
People who come across this older/closed issue may want to look at this newer issue:

[#9529](https://github.com/apache/pinot/issues/9529) — Implement TTL support for Pinot upsert
