### ISSUE TITLE
Tools for pinot data migration (real time and offline)

### ISSUE THREAD

**Issue by ly923976094** [apache/incubator-pinot#3963]
Does pinot have the tools to move data from one machine to another (such as offline old machines)?

**Comment by sunithabeeram** [comment]
@ly923976094 can you provide more details? Are you adding new hosts? Or replacing existing hosts?

**Comment by ly923976094** [comment]
> @ly923976094 can you provide more details? Are you adding new hosts? Or replacing existing hosts?

There is a machine in the pinot cluster that is offline due to resource allocation problem and cost problem. However, the data on this machine is still useful and needs to be analyzed on this pinot cluster. Is there any tool to import the data on this machine into this pinot cluster

**Comment by sunithabeeram** [comment]
The data should be available on the controllers for download by other servers, so you don't need to do anything specifically to move the data. You can update the table's tenant configuration to remove the offline host and add a new one and rebalance the table. You can find REST apis' to do this by hitting your controllers' web port: http://<controllerhost:port>.

(We'll be covering more of the steps in our admin guide soon - https://pinot.readthedocs.io/en/latest/admin_guide.html)

**Comment by ly923976094** [comment]
> The data should be available on the controllers for download by other servers, so you don't need to do anything specifically to move the data. You can update the table's tenant configuration to remove the offline host and add a new one and rebalance the table. You can find REST apis' to do this by hitting your controllers' web port: http://controllerhost:port.
> 
> (We'll be covering more of the steps in our admin guide soon - https://pinot.readthedocs.io/en/latest/admin_guide.html)

I understand. I delete the offline machine tenant tag and  then balance the table
