### ISSUE TITLE
Do we support compression for query results?

### ISSUE THREAD

**Issue by fx19880617** [apache/incubator-pinot#399]
Sometimes I need to return a very large selection query response.

**Comment by kishoreg** [comment]
No, we dont support compression for large results. Definitely a good feature to support. When you say large - does it mean 10k, 100k or 1m?

**Comment by kishoreg** [comment]
Will these queries have group by or just select + filter. I am thinking if its better for servers to send compressed response to broker and broker simply concatenate them and sends it across.

**Comment by fx19880617** [comment]
In this case, the queries are select + filtering.

**Comment by kishoreg** [comment]
Does that mean broker will act as pass through i.e  it just concatenates the responses from the servers.

**Comment by fx19880617** [comment]
Yes, broker will merge data from all the servers then send back, but this may eat too much memory for a single query.

**Comment by antumbde** [comment]
We should support cursor for this use case. We can still compress responses
but cursors will keep brokers simple and we don't pay all the processing
cost upfront.

**Comment by kishoreg** [comment]
@antumbde can you elaborate on the solution. I get the cursor part from client but how would it work between broker and server.

**Comment by antumbde** [comment]
For simple select + filter, we don't need scatter-gather. We can let only
one server process at a time and return compressed response that are passed
through broker. This works for simple select, filter, project queries.

That doesn't work for group-by. But, reading large datasets with group-by
is lower probability use case.

@ Xiang Fu : Is this for presto plugin ? Is the limitation mentioned above
a problem for your use case ?
-Adwait

**Comment by fx19880617** [comment]
Yes, for presto mostly and I need to get this cursor feature in java client implementation. 
My feeling is it's fine to do so as broker could choose when to push down the request to a server.
Also I'm thinking is it possible to write intermediate query response to disk on broker and mmap them for merger or stream out.
