### ISSUE TITLE
Upgrade to use  Kafka release 2.1.1

### ISSUE THREAD

**Issue by mcvsubbu** [apache/incubator-pinot#3998]
Kafka release has a stable version of 2.1.1 (https://kafka.apache.org/downloads)

Pinot should upgrade to a more recent version of Kafka

This release is source incompatible with 0.9 (that Pinot currently uses).  We need to:
* Evaluate the compatiblity of new kafka client with older brokers. If they are not compatbile, then we should upgrade in steps getting to 2.1 eventually.
* Ensure that new Kafka client still provides the functionality we rely on, and move Pinot to use new Kafka clients.

Meanwhile, one solution is to use pluggable streams, but we need to make sure that there is no classpath collision and undesirable behavior

**Comment by mcvsubbu** [comment]
Maybe we can consider moving to this
https://github.com/linkedin/li-apache-kafka-clients if it is compatible

**Comment by kishoreg** [comment]
The first step would be decouple Pinot core from kafka right. Once we have that, we can add multiple implementations likafka, Kafka-0.9.x, Kafka-1.x kafka2.x. 

This will be a good test/use of pluggable streaming source we built.

**Comment by mcvsubbu** [comment]
Sure, we can take all of the current Kafka code to a separate repo that depends on kafka=0.9.x and build other repos for newer Kafkas (if they change source compat). That should be easy to do since we have pluggable streams.

**Comment by kishoreg** [comment]
I was thinking along the same lines. Let’s do that. That will allow us to make sure we are backwards compatible

**Comment by mcvsubbu** [comment]
Not sure how the realtime integration tests will run, though.

**Comment by mcvsubbu** [comment]
And we need to keep kafka client out of the distribution I suppose?

**Comment by kishoreg** [comment]
Yes, we can keep a default implementation but have the ability to configure
something else. This will be similar to remoteFS - > NFS/Azure/HDFS

**Comment by ananthdurai** [comment]
👋 Hi, any update on the Kafka 2.X support? We are running a different version of Kafka to maintain Pinot, would like to move along with the rest of the infrastructure.

**Comment by npawar** [comment]
We're planning to work on this issue this quarter. We (@mcvsubbu  and I) will do some refactoring, such that the kafka code will be separated out as a stream plug in. This will make it easier for folks to plug in the versions of kafka they wish to use. 

Here's the tentative steps we plan to take:
1) Many of our tests are using kafka related classes. We plan to introduce a fake stream, which can be used in all tests. This will help us remove dependency of kafka related classes in all tests. 
2) There are 2 implementations of PartitionFunction, which are using kafka libraries. We plan to abstract those out, and make the stream implementation provide stream specific partition functions.
3)  After completion of above 2 steps, we should be able to pull out kafka related classes into a separate module, say "pinot-kafka-0.9.0.1". This should let us remove kafka dependency from all other modules (i think pinot-common, pinot-core, pinot-controller have kafka as a dependency in their pom).
4) We can then decide whether to keep "pinot-kafka-0.9.0.1" as a module in pinot, or separate it out to another open source repo. This module will serve as an example of exactly what needs to be done to add a plug in)
Will add more details as we iron things out.


After this is completed, you will be able to plug-in your implementations for other kafka versions. @ananthdurai @kishoreg

**Comment by mcvsubbu** [comment]
@ananthdurai can you contribute towards this effort (esp after step 2)?

**Comment by kishoreg** [comment]
@npawar Is there a way to skip the initial steps of adding Fake stream?  Let’s try to abstract the module first. We can keep the dependency for some more time.

**Comment by npawar** [comment]
I tried that @kishoreg . I first moved all Kafka related classes into a pinot-kafka-0.9 module. pinot-kafka-0.9 needed pinot-core  as dependency. And pinot-core and pinot-common needed pinot-kafka-0.9 as test dependency. I encountered errors like "Annotation processing not supported with cyclic module dependencies"
I don't think it should be too much to add a fake stream and change the tests.

**Comment by npawar** [comment]
Had some discussion with @snleee @sunithabeeram  and @mcvsubbu 
1) For tests, we will let pinot-integration-tests have a dependency on pinot-kafka-0.9.0.1. No need to change those tests. For all other tests in pinot-core, pinot-common, pinot-controller, will clean those up to not depend on kafka (some simply are referring to class names), and use FakeStream if needed.
2) @snleee confirmed that we don't need to depend on kafka for Murmur PartitionFunction, and that function can be simply copied over. For ByteArrayPartitionFunction, we will either delete it, or translate the scala code. That way, we will remove kafka dependencies from PartitionFunction.

**Comment by mcvsubbu** [comment]
Next steps after #4252 . We need to decouple pinot completely from any version of kafka:
* Change the integration tests so that appropriate kafka version is injected
* exclude kafka from pinot releases
@ananthdurai can you wok on this as a part of adding support for 2.1.1? thanks

**Comment by mcvsubbu** [comment]
PR #4397

**Comment by fx19880617** [comment]
The above PR tries to add the implementation of Kafka 2.0. 
However something is still missing:
1. pinot-tools and pinot-integration-tests module still have hard dependencies on kafka 0.9. E.g. Start a kafka broker, topic creation, stream data into kafka, etc.
2. No general api to handle the integration tests, I'm not sure if it's worth to let every connector implementation to implement all the surrounding util impls.

**Comment by fx19880617** [comment]
PR https://github.com/apache/incubator-pinot/pull/4445 abstracted Kafka connector into a runtime dependency. 

PR #4397  implements Kafka 2.0 connectors and make the build and release to use different profiles. 
By default, still include kafka 0.9 and users could use `-Dkafka.version=2.0` to include Kafka 2.0 instead of Kafka 0.9.
