### ISSUE TITLE
Failure to retrieve data after adding column to table schema. 

### ISSUE THREAD

**Issue by chenboat** [apache/incubator-pinot#4029]
We recently added a column A with some default value to a Pinot table T (with offline tables). When we issues query like
     select A, other_existing_column from  T where key = "some_value"

It fails to retrieve records inserted before the column addition. Ideally the query should show the record with default value in column A. On the other hand, when we use 
    select  other_existing_column from  T where key = "some_value"
we can get the record.  

Restarting the Pinot servers does not help either in this case. We know the record is in the offline servers.

**Comment by icefury71** [comment]
I believe we need to enable this config in the servers "enable.default.columns=true" . This is necessary for the default columns to be populated for older segments:

https://github.com/apache/incubator-pinot/blob/master/pinot-core/src/main/java/org/apache/pinot/core/segment/index/loader/SegmentPreProcessor.java#L87

**Comment by Jackie-Jiang** [comment]
@icefury71 is right. We introduced this configuration to test out the default column feature long time ago, and didn't remove it since then. #4073 this pr will enable the default column always.
