### ISSUE TITLE
Support variable byte no dictionary columns in Consuming segments

### ISSUE THREAD

**Issue by mcvsubbu** [apache/incubator-pinot#4034]
In realtime consuming segemnts, we don't support STRING or BYTES data type. We should be able to add it using the class MutableOffHeapByteArrayStore

**Comment by siddharthteotia** [comment]
Will work on this

**Comment by siddharthteotia** [comment]
PR https://github.com/apache/incubator-pinot/pull/4791 merged fixing this issue
