### ISSUE TITLE
Wrong command/config to build ?

### ISSUE THREAD

**Issue by katewang0710** [apache/incubator-pinot#4114]
Hi,

I an pretty new to this project. It might be some config issue in my side? Could you give some help ? Thanks

$ mvn clean install -DskipTests -Pbin-dist

[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Users/---/incubator-pinot/pinot-core/src/main/java/org/apache/pinot/core/segment/memory/PinotByteBuffer.java:[29,16] cannot find symbol
  symbol:   class Cleaner
  location: package sun.misc
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Pinot 0.2.0-SNAPSHOT:
[INFO] 
[INFO] Pinot .............................................. SUCCESS [  4.980 s]
[INFO] Pinot Filesystem ................................... SUCCESS [  2.013 s]
[INFO] Pinot Common ....................................... SUCCESS [ 18.733 s]
[INFO] Pinot Transport .................................... SUCCESS [  4.781 s]
[INFO] Pinot Core ......................................... FAILURE [  7.175 s]
[INFO] Pinot Server ....................................... SKIPPED
[INFO] Pinot Controller ................................... SKIPPED
[INFO] Pinot Broker ....................................... SKIPPED
[INFO] Pinot API .......................................... SKIPPED
[INFO] Pinot Hadoop ....................................... SKIPPED
[INFO] Pinot Tools ........................................ SKIPPED
[INFO] Pinot Minion ....................................... SKIPPED
[INFO] Pinot Integration Tests ............................ SKIPPED
[INFO] Pinot Perf ......................................... SKIPPED
[INFO] Pinot Hadoop Filesystem ............................ SKIPPED
[INFO] Pinot Azure Filesystem ............................. SKIPPED
[INFO] Pinot ORC .......................................... SKIPPED
[INFO] Pinot Distribution ................................. SKIPPED
[INFO] Pinot Parquet ...................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  38.113 s
[INFO] Finished at: 2019-04-13T12:15:29-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project pinot-core: Compilation failure
[ERROR] /Users/---/incubator-pinot/pinot-core/src/main/java/org/apache/pinot/core/segment/memory/PinotByteBuffer.java:[29,16] cannot find symbol
[ERROR]   symbol:   class Cleaner
[ERROR]   location: package sun.misc
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :pinot-core

mvn --version
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T11:41:47-07:00)
Maven home: /Users/--/Downloads/apache-maven-3.6.0
Java version: 11.0.1, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/openjdk-11.0.1.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.4", arch: "x86_64", family: "mac"

**Comment by kgopalakrishna** [comment]
Use jdk 9.

**Comment by kishoreg** [comment]
Pinot uses unsafe api which are deprecated in jdk 11. Use jdk 9 to compile.

**Comment by katewang0710** [comment]
Thanks @kishoreg . It might be better to use safe APIs. There should be some reason that the APIs be deprecated.
Anyway, I will use jdk 9 to compile.
