### ISSUE TITLE
performance bug for misuse of String.replaceAll()

### ISSUE THREAD

**Issue by bd2019us** [apache/incubator-pinot#4115]
Location: 
(1) pinot-common/src/main/java/org/apache/pinot/pql/parsers/Pql2AstListener.java
(2) thirdeye/thirdeye-hadoop/src/main/java/org/apache/pinot/thirdeye/hadoop/push/DeleteOverlappingSegmentsInPinot.java

The string to be replaced is plain string, which does not need to be pre-compiled. Therefore, the method call of String.replaceAll() should be changed to replace() for better performance.

**Comment by Jackie-Jiang** [comment]
@bd2019us Thanks for the fix. The change has been merged.
