### ISSUE TITLE
Issue with ingestion data with empty array

### ISSUE THREAD

**Issue by jamesyfshao** [apache/incubator-pinot#4187]
In a recent [change](https://github.com/apache/incubator-pinot/commit/5c296de1c4b91d4cc3b99ee6ccf15c077f9b4dcc) to pinot ingestion workflow, we refactor the PlainFieldExtractor class to the  DataTypeTransformer class. However, we noticed that in this change, the decoding of an empty array (zero-length array) column caused an exception in indexing and pinot ingestor will throw away such row (causing data loss). After some investigation, the root cause seems to be with[ an array operation](https://github.com/apache/incubator-pinot/commit/5c296de1c4b91d4cc3b99ee6ccf15c077f9b4dcc#diff-6e075be1e432676f216423d6b086ed22R94) without checking the proper length (compare to [origin design](https://github.com/apache/incubator-pinot/commit/5c296de1c4b91d4cc3b99ee6ccf15c077f9b4dcc#diff-b363445cd0a59e1a271f755d944af31fL200) where we perform such check). I wonder if we have already working on fixing this issue. If not, we can look into fixing this issue

**Comment by jamesyfshao** [comment]
@Jackie-Jiang as he is origin author of the previous diff and might have more context.

**Comment by Jackie-Jiang** [comment]
@jamesyfshao Are you using custom record reader? Pinot does not support empty array as input, and record reader should already fill in default value for empty array. You can refer to this method: [https://github.com/apache/incubator-pinot/blob/a7a8bb64b3fd6cc3ed8e8feeb9772404f23aa307/pinot-core/src/main/java/org/apache/pinot/core/data/readers/RecordReaderUtils.java#L208](url)

**Comment by jamesyfshao** [comment]
Yes, we have our own reader for decoding data. This seems to undocumented, could we explain a bit why empty array is not supported? Also, I feel it would be a better user experience if we set empty array to the default value to make it backward compatible as well as consistent with empty value for single value.

**Comment by Jackie-Jiang** [comment]
@jamesyfshao Seems the default value behavior is not documented (was documented before, but might be lost while migrating to the new documentation platform), added #4188 to track that.
Empty array is never supported for historical reason (multi-value forward index encoding), and even for the old behavior, it's replaced by single default value [https://github.com/apache/incubator-pinot/commit/5c296de1c4b91d4cc3b99ee6ccf15c077f9b4dcc#diff-b363445cd0a59e1a271f755d944af31fL255](url)

**Comment by jamesyfshao** [comment]
If that is the case, maybe we can look into extending the behavior of pinot indexing so we use single default value for empty array? Overall it should reduce the chance of other users losing data as a lot of people might have needs to use their own decoders and not all of them follow the same implementation.

**Comment by Jackie-Jiang** [comment]
@jamesyfshao That is a good suggestion, but will also change the existing behavior which might affect other users. One reason we made the change to throw exception instead of silently replace the value is to prevent user got unexpected result (single element array instead of empty array).
We already extract most of the commonly used method into RecordReaderUtils, so if you use the provided method to implement your own record reader, it should be quite straight forward. We'll enhance our documentation so that users don't get confused about the behavior.

**Comment by jamesyfshao** [comment]
If that was the case, I think we can update this part to throw a proper exception instead of ArrayIndexOutOfBound. This would help people to better debug such issue. We can help with this change as it is fairly small

**Comment by Jackie-Jiang** [comment]
@jamesyfshao After consideration, decide to handle empty array (replace with default value) instead of throwing exception: #4196
