### ISSUE TITLE
Replica groups support for realtime

### ISSUE THREAD

**Issue by npawar** [apache/incubator-pinot#4192]
Background, motivation and details in: https://cwiki.apache.org/confluence/display/PINOT/Replica+groups+support+in+realtime

**Phase 1** 
Support for realtime

Steps:
1) Replica group sets to be created when table created/updated with replica group assignment strategy - use same path as for offline

2) StreamPartitionAssignmentGenerator to start reading znode and constructing ReplicaGroup compliant assignment. We have a similar class for offline - ReplicaGroupSegmentAssignmentStrategy. Extract logic for creating replica group segment assignment out of both these classes. 

3) Check RealtimeSegmentsValidationManager handles replica groups correctly. Currently we do a lot of recalculation of partition assignments and rebalance on the fly during segment completion and partitions change

4) Rebalance - make sure ReplicaGroupRebalance can handle both offline as well as realtime tables

5) Routing - combine PartitionAwareOffline and PartitionAwareRealtime to a common code for PartitionAwareRouting. Add config to control the partition pruning for realtime consuming segments.

**Phase 2**
Support for relocation and completed segments

**Comment by mcvsubbu** [comment]
@Jackie-Jiang  I think this featrure is now supported. If so, can you close this issue?

**Comment by Jackie-Jiang** [comment]
@mcvsubbu Yes, all the segment assignment/rebalance/relocation are supported by the new ResourceAssignment. The only part missing is the Routing change.
