### ISSUE TITLE
Support for SQL plans

### ISSUE THREAD

**Issue by sunny209868** [apache/incubator-pinot#4199]
Is there any plan to support SQL? It seems that the current PQL is still not convenient for all kinds of complex queries

**Comment by Jackie-Jiang** [comment]
We have plans to migrate to standard SQL in the future, but the support will still be limited to a subset of all SQL queries for performance concern (e.g. JOIN won't be supported). Currently PQL can cover all the queries we support (nested queries are not supported right now). What kind of complex queries are you referring to?

**Comment by sunny209868** [comment]
For example, Having, the addition, subtraction, multiplication, and division of an aggregate indicator(SUM(a)/SUM(b))

**Comment by Jackie-Jiang** [comment]
@sunny209868 We also have plan for that :P You can check this Pinot fork: https://github.com/winedepot/pinot, and we are planing to merge this into the master.

**Comment by sunny209868** [comment]
> @sunny209868 We also have plan for that :P You can check this Pinot fork: https://github.com/winedepot/pinot, and we are planing to merge this into the master.

**Comment by sunny209868** [comment]
> > @sunny209868 We also have plan for that :P You can check this Pinot fork: https://github.com/winedepot/pinot, and we are planing to merge this into the master.

@Jackie-Jiang  Yes, this idea is similar to mine. It would be better if it can support udf in the later stage
