### ISSUE TITLE
using the command bin/pinot-admin.sh to excute sql,but prompt connection timed out, how can I deal with it?thx

### ISSUE THREAD

**Issue by hhjhbhj** [apache/incubator-pinot#42]

**Comment by jfim** [comment]
What do you mean by the prompt connection timed out? Did you get an error?

**Comment by hhjhbhj** [comment]
when I use the command bin/pinot-admin.sh post, then about five mininutes later, I get the prompt that connection timed out, but when I check the log I can't find any errors.

**Comment by hhjhbhj** [comment]
And I want to know which log4j.properties file it use when it is running, I want to check all the running information, so I need the log4j.

**Comment by Jackie-Jiang** [comment]
Too old, no longer relevant
