### ISSUE TITLE
implement upsert support on pinot

### ISSUE THREAD

**Issue by jamesyfshao** [apache/incubator-pinot#4261]
Pinot is a distributed real-time OLAP engine that can provide second-level data freshness by ingesting kafka events and capacity to manage months of historical data load from various data sources such as HDFS, schemaless, etc. However, Pinot right now mostly functions as an append-only storage system. It doesn’t allow modify/delete of existing records with the exception of overriding all data within a time range with offline tables. This limits the applicability of pinot system due to a lot of use-cases requiring updates to their data due to the nature of their events or needs for data correction/backfill. In order to extend the capacity of pinot and serve more use-cases, we are going to implement the upsert features in Pinot which allows users to update existing records in Pinot tables with its kafka data input stream.

Some initial requirements for the upsert projects:

1. Only support for full update to pinot event

2. Only support for Kafka-compatible queue ingestion model

3. Single pinot server/table can handle 10k/sec ingestion message rate

4. Each pinot server can handle 1 Billion records or 1TB storage

5. Ingestion latency overhead compared to non-upsert model < 1min

6. Query latency overhead compared to non-upsert model < 50%

7. Data retention < 2 weeks

**Comment by jamesyfshao** [comment]
summary on 1st discussion of upsert design (May 15th):

1. @Jackie-Jiang points out that current design of rewriting queries for upsert table is problematic as this cause too much overhead in pinot query process with so many or-conditions. We should look into method to reduce the query overhead in upsert table

2. We should look into message delivery from coordinator service to pinot server. @Jackie-Jiang proposed methods on re-using existing download API on coordinator service to deliver messages from coordinator to server for unified API.

3. How to handle kafka topic partition change. @mcvsubbu suggested that we should look into how to handle accidental expand of kafka topic if that happens.

**Comment by mcvsubbu** [comment]
@jamesyfshao can you add a pointer to your design doc in this issue? thanks

**Comment by jamesyfshao** [comment]
> @jamesyfshao can you add a pointer to your design doc in this issue? thanks

please use this design doc for now https://docs.google.com/document/d/1SFFir7ByxCff-aVYxQeTHpNhPXeP5q7P4g_6O2iNGgU/edit. We might have permission issue for new ppl as it is still WIP to keep the discussion more organized. Once it is more close to "ready" state I will put it on apache site

**Comment by yupeng9** [comment]
It has been a while since the upsert work started. We'd like to reflect on the challenges encountered, share some learnings and also a [revisit on the upsert design](https://docs.google.com/document/d/1qljEMndPMxbbKtjlVn9mn2toz7Qrk0TGQsHLfI--7h8/edit#heading=h.lsfmyoyyxtgt).

**Comment by yupeng9** [comment]
Added the docs at https://docs.pinot.apache.org/basics/data-import/upsert
