### ISSUE TITLE
Cleanup pinot-api interfaces

### ISSUE THREAD

**Issue by sunithabeeram** [apache/incubator-pinot#4265]
This issue tracks discussion in https://github.com/apache/incubator-pinot/pull/4243. The current structure of the module isn't clean in terms of relationship within the classes/interfaces in the module and its hard to understand which of the interfaces are truly external/extensible and which are not. Ideally, most all classes in pinot-api should be considered "external" facing.

Some specific issues from #4243: ConnectionFactory is considered to be the external facing interface; however the functionality is exposed through static methods and a specific transport-factory implementation is tied to the class that makes it inflexible to drop in other transports (For e.g., its unclear how one might use a Https transport).

It would be good to clarify/cleanup the interfaces.

**Comment by kishoreg** [comment]
@sunithabeeram, this module was put together in a very short time frame and needs a major rehaul. It caters to the basic functionalities and works well for simple cases. Advanced users end up having their own clients based on the pinot REST API (e.g rest.li).

It's better to revisit this module once we fix the pinot SQL interface and add support for calcite.

**Comment by sunithabeeram** [comment]
@kishoreg in the interim, it will be great if we can figure out how changes to this code will be handled. Should users be allowed to contribute back to this while its in 'deprecated' state? Its not clear to me which interfaces could have been extended by users that may break as a result of changes. As long as we have guidelines around that, we should be good. Thanks!

**Comment by Jackie-Jiang** [comment]
This is done, and the replacement is the `pinot-client` package
