### ISSUE TITLE
Launching in local leads to ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by Tricalt** [apache/incubator-pinot#4281]
After following the Quick Start [guide](https://thirdeye.readthedocs.io/en/latest/quick_start.html) and launching frontend with 
`./run-frontend.sh`
I faced ERR_SSL_PROTOCOL_ERROR that prevented frontend from loading.

**Comment by xiaohui-sun** [comment]
It was because of the HTTPS redirect we recently added. I reverted the change. Please try again. @Tricalt.

@harleyjj  We need to figure out how to get the environment settings without ember-cli running.
