### ISSUE TITLE
what is the difference between Pinot and Druid

### ISSUE THREAD

**Issue by JackyYangPassion** [apache/incubator-pinot#4400]
what is the difference between Pinot and Druid:
1. in  realtime ingest
2. in segment

**Comment by sunny209868** [comment]
This article is very detailed. https://medium.com/@leventov/comparison-of-the-open-source-olap-systems-for-big-data-clickhouse-druid-and-pinot-8e042a5ed1c7

**Comment by JackyYangPassion** [comment]
3Q

**Comment by sunny209868** [comment]
> 3Q

https://github.com/apache/incubator-pinot/issues/3，this issues can help you @JackyYangPassion

**Comment by kishoreg** [comment]
Real-time Ingest
- Druid supports two modes Push (Tranquility) and Pull (Kafka Indexing Service). Push has the limitation that late arriving events (after a certain window) will be dropped. I am not sure if the limitation applies to the pull mode.  https://druid.apache.org/docs/latest/ingestion/stream-ingestion.html

Pinot support ingesting data from directly from Kafka. We support two modes - using high level Kafka Consumer or low level Kafka consumer. Using low level you can get exactly once semantics. Pinot does not drop late arriving events.

Segment
- Pinot & Druid have their own custom columnar format to store data. At a high level, a segment contains forward index (mostly dictionary encoded) and inverted index (optional). Pinot has additional indexing schema known as star-tree index which can speed up Aggregations. https://engineering.linkedin.com/blog/2019/06/star-tree-index--powering-fast-aggregations-on-pinot


See slides 21, 28, 35 for performance comparison between Pinot and Druid. https://www.slideshare.net/KishoreGopalakrishna/building-real-time-analytics-applications-using-pinot-a-linkedin-case-study

**Comment by JackyYangPassion** [comment]
Firstly :thank you for your attention!
I agree with that Druid supports two modes Push (Tranquility) and Pull (Kafka Indexing Service) ;But Kafka Indexing Service also support  exactly once semantics.
I am very interested in Pinot star-tree index

**Comment by JackyYangPassion** [comment]
Pinot  can support exactly count distinct in realtime and index-hadoop?

**Comment by mamtasharma311** [comment]
What is Apache Pinot Architecture?

[https://www.decipherzone.com/blog-detail/apache-pinot-architecture](https://www.decipherzone.com/blog-detail/apache-pinot-architecture)
First created at LinkedIn to empower business and user-facing problems, Pinot was then donated to Apache in 2019. Apache Pinot, an open-source, real-time, column-oriented, distributed Online Analytical Processing (OLAP) datastore, written in [Java](https://www.decipherzone.com/java-development-services). Pinot is designed to deliver low-latency, real-time analytics. Apache Pinot is built to horizontally scale when needed to help scale larger data sets and higher query rates.
