### ISSUE TITLE
No documentation on setting up email alerts in Thirdeye

### ISSUE THREAD

**Issue by vasilije90** [apache/incubator-pinot#4406]
Hi,

I am having difficulties testing Thirdeye alerting and receiving emails on my test alerts.
There is not much documentation on the issue and coupled with other bugs that break the interface, it prevents me from testing the tool.
Is there a chance that a simple tutorial can be written that covers everything from importing jdbc mysql metric, creating an alert, adding smtp server and sending out an email to specific recepients?

**Comment by xiaohui-sun** [comment]
I updated the configuration docs. Please take a look  @vasilije90 
https://thirdeye.readthedocs.io/en/latest/configuration.html

**Comment by vasilije90** [comment]
Looks good @xiaohui-sun 

It covers most of the issues I faced setting it up. 
A phantomJS install step would be nice, or at least a pointer.
I assume most systems won't have it installed.
