### ISSUE TITLE
Alert screen breaks in Thirdeye

### ISSUE THREAD

**Issue by vasilije90** [apache/incubator-pinot#4407]
When using jdbc connection and making sure that registered alert is present and inspecting anomalies, the tool breaks.
Due to my understanding, this is due to imputeExpectedTimestamps function trying to iterate on a dataset on a millisecond level leading to java.lang.OutOfMemoryError
Importing data on daily level should solve the issue, but due to the previous bug reported (#4332) this might prove difficult. 

`NFO  [2019-07-09 11:30:02,929] org.apache.pinot.thirdeye.datasource.sql.SqlResponseCacheLoader: Running SQL: SELECT date, SUM(clickouts) FROM dwh.agg_kpi_clickouts WHERE  DATE_PART( EPOCH, TO_DATE(CAST(date AS VARCHAR), 'YYYY:MM:DD HH:MI:SS')) BETWEEN 1562450400 AND 1562709600 GROUP BY date LIMIT 100000
ERROR [2019-07-09 11:30:33,143] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: a16773b6bf11e63c
! java.lang.OutOfMemoryError: Java heap space
! at java.util.Arrays.copyOf(Arrays.java:3181)
! at java.util.ArrayList.grow(ArrayList.java:265)
! at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:239)
! at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:231)
! at java.util.ArrayList.add(ArrayList.java:462)
! at org.apache.pinot.thirdeye.dashboard.resources.v2.RootCauseMetricResource.imputeExpectedTimestamps(RootCauseMetricResource.java:460)
! at org.apache.pinot.thirdeye.dashboard.resources.v2.RootCauseMetricResource.getTimeSeries(RootCauseMetricResource.java:417)
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
! at java.lang.reflect.Method.invoke(Method.java:498)
! at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
! at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
! at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
! at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
! at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
! at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
! at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
! at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)`

**Comment by xiaohui-sun** [comment]
In ThirdEye we handles the epoch time by aggregating to minute level, but that is for Pinot data source only.
We should handle this for MySQL as well.
