### ISSUE TITLE
Thirdeye anomaly page breaks after manually registering anomaly

### ISSUE THREAD

**Issue by vasilije90** [apache/incubator-pinot#4408]
Hi,

After manually registering anomaly, the Thirdeye anomaly page breaks with
GET /anomalies/search/time/1562588143335/1562674543336/1?filterOnly=true HTTP/1.1" 400 58

I am unclear on why this happens since there are no more detail logs I can check.

**Comment by xiaohui-sun** [comment]
Is that the same issue as loading the epoch time table? @vasilije90

**Comment by vasilije90** [comment]
Hey @xiaohui-sun. I don't think it is. It usually happens only after manually registering an anomaly.
Although the process is a success, and the anomaly is visible in the alert tab, I still face issues with accessing anomaly page as described above. There are no more detailed logs I could provide.

Dropping MySql database is a workaround, and automatically detected anomalies don't break the interface.

**Comment by xiaohui-sun** [comment]
@vasilije90  can you see any error message from log?

**Comment by vasilije90** [comment]
I got nothing on the first try, only a 400. I will try again and post any updates I find.
