### ISSUE TITLE
Thirdeye documentation

### ISSUE THREAD

**Issue by vasilije90** [apache/incubator-pinot#4507]
Hi,

I recently had a chat with @kishoreg  and he asked if I could contribute with a document detailing what could be added to the documentation from my perspective. 

I am including it below and I hope some of these could be addressed to help new users. 

`Thoughts on Thirdeye Documentation 
1. Getting started guide
The current getting started does not instruct user step by step how to get to the point where alert is sent to him via email.
Structure:
    1. Installing and building the tool / Docker image setup?
    2. Adding a simple rule (with screenshots)
    3. Adding smtp configs
    4. Specifying email details
I approached this by creating a MySQL docker image and my own setup just for enabling all of these features to work.
It could be potentially a good way to do it that way instead of h2db where there were issues connecting both dashboard and anomaly service at the same time.
2. Migrating to production
Currently productionizing the tool is not well covered in terms of a stable infra setup on should have to have tool running 99% of the time.
Structure:
    1. Migration to MySQL (optionally packaged in one config)
    2. Suggestions on machine types, application requirements and general info on scalability (no idea how it would work with 5 vs 50 users)
    3. Auth guide, setting up authentication on login
3. Admin section
There are a lot of admin tools that are not well covered currently
Open questions:
    1. Admin tool documentation on port 1427
    2. Documentation on REST API calls and automation of anomaly configurations remotely (teams in Omio are very interested in this)
    
3. Models and checks
Checks are documented and it is easy to get started. Some things are missing though
Open questions:
    1. How does preview work, and how much data do models take to calculate predictions
    2. How do all ML features work and where do they reside
    3. How to test different configurations without GUI
4. Kafka
A simple guide or pinot setup to get data from Kafka would be very helpful. `

**Comment by sunny19930321** [comment]
It is better To provide the following methods of calculation: baseline, Percentage Change, ChangeIn Contribution, Contribution To Overall Change, and so on

**Comment by jomach** [comment]
a guide how to perform authentication on kafka
