### ISSUE TITLE
Support simpler streams

### ISSUE THREAD

**Issue by lsabi** [apache/incubator-pinot#4574]
As a new user, the kafka streaming option is quite difficult to understand and use. Is there any plan to support it more easily?

As far as I understood from the tutorial, I have to write the code on my own and compile the entire project if I want to consume data from a kafka topic. Though, can I do it for multiple topics/streams (simultaneously)? What about upgrading the system? Will I have to recompile my code at any update and replace it?

Thanks

**Comment by snleee** [comment]
1. Pinot currently allows you to consume from a single Kafka topic.
2. Pinot currently supports Kafka (0.9.x and 2.x). You don't need to write any code if you are trying to use Kafka for consumption. If you configure `TableConfig` correctly, it should work. You can refer to https://pinot.readthedocs.io/en/latest/pluggable_streams.html#pluggable-streams
Also, you can start with trying out `quick-start-realtime.sh` script, this will bring up the local kafka cluster, create a topic, and start to emit some data to the topic, which is consumed by Pinot.

If you have more questions, feel free to join Slack for the support. https://tinyurl.com/pinotSlackChannel

**Comment by lsabi** [comment]
1. Overall only one? Or you mean one per table?
2. That part of the docs was confusing me. Do I have or do I have not to compile Pinot myself with the kafka extension?

Thanks.

**Comment by snleee** [comment]
@lsabi
1. One per table
2. Which version of Kafka are you using? By default, it will build using Kafka `0.9.x`. If you want to run against Kafka 2.0, you will need to build the jar from the source running the following commands `mvn clean package -DskipTests -Pbin-dist -Dkafka.version=2.0`.

**Comment by lsabi** [comment]
1. That's not bad, I thought one per database
2. Too bad, I'm using kafka 2.3. I'll compile it myself when I have time

Though, the documentation is not super clear nor easy to understand for a beginner.

Thanks for the help
