### ISSUE TITLE
Add documentation on schema

### ISSUE THREAD

**Issue by snleee** [apache/incubator-pinot#4596]
We currently don't have a good documentation on schema. We should add one at https://pinot.readthedocs.io/en/latest

1. What are dimensions, metrics and time column
2. What kind of types are supported for each type
3. What kind of other options that we have (`defaultValue, single vs multi value...etc`)

**Comment by mayankshriv** [comment]
This was addressed in https://github.com/apache/incubator-pinot/pull/4637.
