### ISSUE TITLE
Can not find a deserializer for non-concrete Map type

### ISSUE THREAD

**Issue by arthuersundar** [apache/incubator-pinot#4603]
I deployed the Apache Pinot in Azure kubernetes services following the below link.

https://github.com/jfim/docker-pinot/tree/master/azure

Getting some error. GET seems to be working fine, but when i do a POST (post schema, post table) it is throwing error. 

Error :
Can not find a deserializer for non-concrete Map type [map type; class javax.ws.rs.core.MultivaluedMap, [simple type, class java.lang.String] -> [collection type; class java.util.List, contains [simple type, class java.lang.String]]]
 at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@343026fa; line: 1, column: 1]
![Screen Shot 2019-09-09 at 9 58 58 PM](https://user-images.githubusercontent.com/41527365/64581490-fc488900-d34f-11e9-8cc5-48a7878c2428.png)

**Comment by snleee** [comment]
The docker image that you mentioned is very old one (2 yrs ago) and may contain very old version of Pinot. Can you try with https://github.com/apache/incubator-pinot/tree/master/docker ?

**Comment by AnishKanth** [comment]
Facing the same issue with above mentioned docker image(https://github.com/apache/incubator-pinot/tree/master/docker)

Cannot find a deserializer for non-concrete Map type [map type; class javax.ws.rs.core.MultivaluedMap, [simple type, class java.lang.String] -> [collection type; class java.util.List, contains [simple type, class java.lang.String]]] at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 1]

**Comment by AnishKanth** [comment]
> The docker image that you mentioned is very old one (2 yrs ago) and may contain very old version of Pinot. Can you try with https://github.com/apache/incubator-pinot/tree/master/docker ?

Facing the same issue with docker from above mentioned path (https://github.com/apache/incubator-pinot/tree/master/docker)

Cannot find a deserializer for non-concrete Map type [map type; class javax.ws.rs.core.MultivaluedMap, [simple type, class java.lang.String] -> [collection type; class java.util.List, contains [simple type, class java.lang.String]]] at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 1]

**Comment by fx19880617** [comment]
Hi @AnishKanth, could you put the post request you are using? Also have you tried out `pinot-admin` command?

**Comment by AnishKanth** [comment]
> Hi @AnishKanth, could you put the post request you are using? Also have you tried out `pinot-admin` command?

Please find the python Request:
import requests
import json
URL = "http://13.89.201.184:9000/schemas/validate"
data = { "schemaName": "transcripthh", "dimensionFieldSpecs": [  { "name": "studentID", "dataType": "STRING" },  {  "name": "firstName", "dataType": "STRING" }, { "name": "lastName", "dataType": "STRING" }, { "name": "gender", "dataType": "STRING" }, { "name": "subject", "dataType": "STRING" } ], "metricFieldSpecs": [ { "name": "score", "dataType": "FLOAT" } ] }
payload = json.dumps(data)
headers = {
                'content-type': "application/json"
            }
response = requests.request("POST", URL, data=payload,headers=headers)

Curl command:
curl -X POST --header 'Content-Type: application/json' --header 'Accept: text/plain' -d '{ \ 
   "schemaName": "transcript", \ 
   "dimensionFieldSpecs": [ \ 
     { \ 
       "name": "studentID", \ 
       "dataType": "STRING" \ 
     }, \ 
     { \ 
       "name": "firstName", \ 
       "dataType": "STRING" \ 
     }, \ 
     { \ 
       "name": "lastName", \ 
       "dataType": "STRING" \ 
     }, \ 
     { \ 
       "name": "gender", \ 
       "dataType": "STRING" \ 
     }, \ 
     { \ 
       "name": "subject", \ 
       "dataType": "STRING" \ 
     } \ 
   ], \ 
   "metricFieldSpecs": [ \ 
     { \ 
       "name": "score", \ 
       "dataType": "FLOAT" \ 
     } \ 
   ] \ 
 }' 'http://localhost:9000/schemas/validate'

**Comment by fx19880617** [comment]
I'm still looking into this issue of POSTing data.
Meanwhile there is a workaround by dumping the schema into a file and upload the schema file.
Below is an example code snippet in python:

```python
import json
temp_schema_path='/tmp/sample_schema.json'
schema_payload = { "schemaName": "transcript", "dimensionFieldSpecs": [ { "name": "studentID", "dataType": "STRING" }, { "name": "firstName", "dataType": "STRING" }, { "name": "lastName", "dataType": "STRING" }, { "name": "gender", "dataType": "STRING" }, { "name": "subject", "dataType": "STRING" } ], "metricFieldSpecs": [ { "name": "score", "dataType": "FLOAT" } ] }

with open(temp_schema_path, 'w') as fp:
    json.dump(schema_payload, fp)


import requests
url_origin = "http://localhost:9000/schemas"
with open(temp_schema_path, 'rb') as f:
    r = requests.post(url_origin, files={'sample_schema.json': f})
    print(r.status_code)
```

**Comment by AnishKanth** [comment]
> I'm still looking into this issue of POSTing data.
> Meanwhile there is a workaround by dumping the schema into a file and upload the schema file.
> Below is an example code snippet in python:
> 
> ```python
> import json
> temp_schema_path='/tmp/sample_schema.json'
> schema_payload = { "schemaName": "transcript", "dimensionFieldSpecs": [ { "name": "studentID", "dataType": "STRING" }, { "name": "firstName", "dataType": "STRING" }, { "name": "lastName", "dataType": "STRING" }, { "name": "gender", "dataType": "STRING" }, { "name": "subject", "dataType": "STRING" } ], "metricFieldSpecs": [ { "name": "score", "dataType": "FLOAT" } ] }
> 
> with open(temp_schema_path, 'w') as fp:
>     json.dump(schema_payload, fp)
> 
> 
> import requests
> url_origin = "http://localhost:9000/schemas"
> with open(temp_schema_path, 'rb') as f:
>     r = requests.post(url_origin, files={'sample_schema.json': f})
>     print(r.status_code)
> ```

Now I can able to upload the schema through API itself.. Thanks a lot @fx19880617
