### ISSUE TITLE
Provide code and documentation that generates ThirdEye Docker image

### ISSUE THREAD

**Issue by JohnTheLearner** [apache/incubator-pinot#4689]
Generate Dockerfile and ancillary code that generates a ThirdEye (TE) demo Docker image for easy and reproducible evaluation, development, and testing.  

This can help prospective TE community members evaluate the project and contribute.

This containerization can later be extended to wrap context around the running of TE by connecting to various data sources, running in different compute environments such as in k8s, or other user-specified purposes.

**Comment by xiaohui-sun** [comment]
Sounds like a great idea!
