### ISSUE TITLE
support String UDFs

### ISSUE THREAD

**Issue by kishoreg** [apache/incubator-pinot#4856]
Support string operations like substring, uppercase, lowercase, reverse etc.

Follow pattern similar to Math operators.

https://github.com/apache/incubator-pinot/blob/master/pinot-core/src/main/java/org/apache/pinot/core/operator/transform/function/SingleParamMathTransformFunction.java

**Comment by elonazoulay** [comment]
I would like to work on this as we have a use case for simple string functions.
