### ISSUE TITLE
Make PQL case insensitive

### ISSUE THREAD

**Issue by kishoreg** [apache/incubator-pinot#4902]
Table Names, Column Names, Function Names are probably case sensitive in Pinot. As a result
- hard to write queries without looking at the schema 
- Makes it harder to integrate with other tools such as Presto, powerBI etc which convert some fragments into lower case.

**Comment by siddharthteotia** [comment]
Big +1

**Comment by Jackie-Jiang** [comment]
Agree on table name and column name (should already be case sensitive). Why should function name be case sensitive? Based on this article, function name should not be case sensitive: http://www.informit.com/articles/article.aspx?p=2036581&seqNum=3

**Comment by siddharthteotia** [comment]
> Agree on table name and column name (should already be case sensitive). Why should function name be case sensitive? Based on this article, function name should not be case sensitive: http://www.informit.com/articles/article.aspx?p=2036581&seqNum=3

I think the proposal is to make them case-insensitive -- which is in accordance with what the link suggests

**Comment by Jackie-Jiang** [comment]
My mistake. Then I am okay making it case insensitive. Not sure if there are clients requiring case sensitive table/column names.

**Comment by kishoreg** [comment]
Does anyone know which parts are case sensitive today in Pinot?

**Comment by Jackie-Jiang** [comment]
All the names except for function names (table name, column name, tenant name, tag name) are case sensitive.

**Comment by kishoreg** [comment]
```
TableName: baseballStats
Columns: "AtBatting", "G_old", "baseOnBalls", "caughtStealing", "doules", "groundedIntoDoublePlays",
 "hits", "hitsByPitch", "homeRuns", "intentionalWalks", "league", "numberOfGames", 
"numberOfGamesAsBatter", "playerID", "playerName", "playerStint", "runs", "runsBattedIn", 
"sacrificeFlies", "sacrificeHits", "stolenBases", "strikeouts", "teamID", "tripples", "yearID"
```
The following queries fail
```diff
- select * from baseballstats limit 10 //lower case table name
- select numberofgames from baseballStats limit 10 //lower case numberofgames
+ select SUM(numberOfGames) from baseballStats limit 10 //agg functions
+ select sum(numberOfGames) from baseballStats limit 10 //agg function

```
