### ISSUE TITLE
StartKafkaCommand does not consider command line arguments

### ISSUE THREAD

**Issue by raymondlam12** [apache/incubator-pinot#5041]
You can try this by running ./pinot-admin.sh StartKafka with some parameters (e.g. zkAddress will be localhost:2191 despite passing in a -zkAddress argument).

**Comment by fx19880617** [comment]
Thanks for raising this issue.

Seems like this code doesn't take account any passing parameters:
```
https://github.com/apache/incubator-pinot/blob/master/pinot-tools/src/main/java/org/apache/pinot/tools/admin/command/StartKafkaCommand.java
```
