### ISSUE TITLE
Run the RealtimeSegmentvalidationManager on demand

### ISSUE THREAD

**Issue by npawar** [apache/incubator-pinot#5263]
When realtime consumption goes into some erroneous state, we rely on the RealtimeSegmentValidationManager to fix it. This by default runs at an hourly frequency.
There have been frequent asks for being able to run it on demand, in order to fix problems faster if they've been spotted.

@kishoreg @mcvsubbu

**Comment by mcvsubbu** [comment]
Once a pinot cluster is up and running in production, we really do NOT want to do these runs manually triggered.  There are race conditions that can happen if these are run together or within a short period of interval (we only fix segments if they are in the state for a long time).

For someone just starting out to experiment with a table, it should be simple to just drop the table and re-create it, right? 

Or, am I missing something here?

We can provide a command-line based fixer (with a note that you run it at your own risk if your table is in production), maybe.

**Comment by kishoreg** [comment]
This has been requested too many times - what are the scenarios a segment will get into error state or stop consumption and what does the validation manager do internally?

**Comment by mcvsubbu** [comment]
https://cwiki.apache.org/confluence/display/PINOT/Consuming+and+Indexing+rows+in+Realtime#ConsumingandIndexingrowsinRealtime-Self-healingconsumption

**Comment by npawar** [comment]
Closing this issue, as this is a subset of https://github.com/apache/incubator-pinot/issues/6812. Looks like there is agreement to add this feature on 6812, so we don't need to continue this old thread anymore.
