### ISSUE TITLE
Add support for protobuf input format

### ISSUE THREAD

**Issue by npawar** [apache/incubator-pinot#5269]
Currently the supported input formats for batch ingestion are CSV, AVRO, JSON, Parquet, Thrift, ORC.

Add support for Protobuf.

**Comment by reallocf** [comment]
Hey @npawar - I'm interested in working on this one. Would be my first time contributing to the project, would love to help! 🎉

I'm guessing I'll create another `pinot-input-format` and mirror `pinot-json` or `pinot-csv` or `pinot-parquet`. Then update `RecordReaderFactory` in `pinot-spi` and probably the `CreateSementCommand` in `pinot-tools`. Where else should I be updating? I'm sure I'm missing a bunch of places :)

**Comment by kishoreg** [comment]
You pretty much got everything right. I think @KKcorps has already started working on this. Can you pick up the support for filtering during ingestion? https://github.com/apache/incubator-pinot/issues/5268

**Comment by reallocf** [comment]
@kishoreg - thanks for letting me know! Definitely don't want to duplicate work 👍 will take a look at #5268

**Comment by KKcorps** [comment]
Taking this up!
