### ISSUE TITLE
Add the geospatial support

### ISSUE THREAD

**Issue by yupeng9** [apache/incubator-pinot#5280]
Geospatial data has been widely used across the industry, spanning multiple verticals, such as ride sharing and delivery, transportation infrastructure, defense and intel, public health. Deriving insights from timely and accurate geospatial data could enable mission-critical use cases in the organizations and fuel a vibrant marketplace across the industry. It will enable many use cases the geospatial support in Pinot.

**Comment by yupeng9** [comment]
Design Doc https://docs.google.com/document/d/1Mkm5RHS_tof-vIUt5-UNeOgRYSBAN6M_pN-hedV6Q0g/edit#

**Comment by snleee** [comment]
@yupeng9 can you grant the access to everyone? I don't have the access to the doc.

**Comment by yupeng9** [comment]
Unfortunately I was not able to configure the sharing policy for anyone outside the company with the link to access, due to certain restrictions. Please request access and I will grant it. I will also put up a version under the Apache Wiki soon.

**Comment by yupeng9** [comment]
A copy of the proposal is added to Apache wiki at [here](https://cwiki.apache.org/confluence/display/PINOT/%5BProposal%5D+Geospatial+support+in+Pinot). Please keep the discussion on the google doc.

**Comment by yupeng9** [comment]
The design of the geospatial indexing is updated and added to the design doc  [here](https://docs.google.com/document/d/1Mkm5RHS_tof-vIUt5-UNeOgRYSBAN6M_pN-hedV6Q0g/edit#)
