### ISSUE TITLE
Fix start zookeeper command

### ISSUE THREAD

**Issue by kishoreg** [apache/incubator-pinot#5294]
The startZookeeper command deletes the directory on exit. We should not delete it and add an option to clean the directory. Also, it does not use the -dataDir option.

``` public static File createAutoDeleteTempDir() {
    File tempdir = Files.createTempDir();
    tempdir.delete();
    tempdir.mkdir();

    tempdir.deleteOnExit();
    return tempdir;
  }

```

**Comment by shireennagdive** [comment]
Working on it!

**Comment by fx19880617** [comment]
https://github.com/apache/incubator-pinot/pull/5295

**Comment by fx19880617** [comment]
> Working on it!

Thanks for taking it, there is already a PR around it, feel free to take a look and review it!

**Comment by shireennagdive** [comment]
Cool, I think this issue can be removed now
