### ISSUE TITLE
Add date time transform functions

### ISSUE THREAD

**Issue by npawar** [apache/incubator-pinot#5313]
This is a followup to: https://github.com/apache/incubator-pinot/pull/5312

We need to exhaustively add a lot of time transformation functions. This is part of the broader task: https://docs.google.com/document/d/1SU1jCjfsIDSA960fD5YWQbD72p8UdGF0c7CroFNt9Ho/edit#heading=h.y1084mvhfcft

**Comment by npawar** [comment]
https://github.com/apache/incubator-pinot/issues/2756

**Comment by npawar** [comment]
One thing to keep in mind when designing: In the case of Simple Date Format, we don't want to create an instance of SDF formatter for every row.

**Comment by npawar** [comment]
@reallocf does this look like something you can help out with?

**Comment by reallocf** [comment]
@npawar yes, would love to help with this! Will look into it later today and ask any questions I have here. Thanks!

**Comment by reallocf** [comment]
Chatted with @npawar a bit over Slack. She added a number of the functions here: https://github.com/apache/incubator-pinot/pull/5324/files so I'm focusing mostly on LocalDateTime conversions here.

The interfaces should be something like:
```
LocalDateTime toLocalDateTime(Long millis, String pattern)

Long fromLocalDateTime(LocalDateTime millis)
```

The core complexity here is in not creating a new SimpleDateFormatter for each row (as Neha already mentioned). Right now, all DateTimeFunctions are static - if we were to write similar static functions we would either need to create a new SimpleDateFormatter for each row (too slow) or create a simple cache for SimpleDateFormatters (the joys of cache invalidation...). So, the better approach is to refactor the FunctionRegistry to allow non-static functions to be processed so we can have some shared memory between rows.

I'm exploring the best way to go about this now, using the usage of TransformFunctions as an example.

**Comment by reallocf** [comment]
With https://github.com/apache/incubator-pinot/pull/5326 merging, can we close this? Or should we leave it open for some follow-up work?
