### ISSUE TITLE
Query Supporting datetime column comparing against currenttime

### ISSUE THREAD

**Issue by rasin215** [apache/incubator-pinot#5401]
Feature Request.
Most of the time you need a report where we need to compare data against current date/time. Currently there is no function which is supporting to compare data against current data/time.

e.g select * from table_name where est_date < now()

This query will help to build dashboard for data which is missing eta / est_date comparing against current data/time

**Comment by fx19880617** [comment]
https://github.com/apache/incubator-pinot/pull/5406

**Comment by fx19880617** [comment]
This is supported in current master now.
