### ISSUE TITLE
pinot-ingestion-job.sh is broken after latest master code change in IngestionJobLauncher

### ISSUE THREAD

**Issue by Manoj-Singh-11** [apache/incubator-pinot#5404]
/usr/local/apache-pinot/bin/pinot-ingestion-job.sh /tmp/raw_data/abc.yml
Error: Main method not found in class org.apache.pinot.spi.ingestion.batch.IngestionJobLauncher, please define the main method as:
   public static void main(String[] args)
or a JavaFX application class must extend javafx.application.Application

 main method from IngestionJobLauncher is removed.

**Comment by fx19880617** [comment]
https://github.com/apache/incubator-pinot/pull/5403
