### ISSUE TITLE
Functions in Pinot

### ISSUE THREAD

**Issue by kishoreg** [apache/incubator-pinot#5416]
We have multiple types of Functions in Pinot
- AggregationFunction
  - Used during query execution
  - Stateful 
  - aggregate method can be invoked multiple times with blockValMap
  - follows map/combine/reduce paradigm
- TransformFunction
  - used during query execution
  - stateless
  - transform method is invoked with projectionBlock as input
  - outputs another block (length of output block is same as input block)
- IngestionTransformFunction
  - Used during ingestion (real-time and batch)
  - stateless
  - takes Generic Row and returns one value
- ScalarFunction (this is basically any java function)
 - These are pure java functions that take a bunch of arguments and return a value

Most of the utility functions should be represented as ScalarFunctions
IngestTransformFunction, TransformFunction can be syntactic sugars on top of these scalar functions.

We are seeing the same function being needed in transform, ingestion, query parsing  (e.g. date time functions) and we have to write the same version multiple times. Should we write generic wrappers around Scalar Function for ingestion, transform?

**Comment by fx19880617** [comment]
My overall feeling is that we should just have two types of functions:
- aggregation: which knows how to do accumulate 
- transform: which is pure transform, given value(s).

ingestion/scalar are just part of transform function with same/different apis.

**Comment by mayankshriv** [comment]
We can create a hierarchy, with top level classification as:
1. Aggregation: m rows input k rows output (m <=k)
2. Transform: 1 row input 1 row output

Underneath 2 we can have, transform/scalar/ingestion
