### ISSUE TITLE
[Docs] Running Pinot in Kubernetes: Load Demo data source issue

### ISSUE THREAD

**Issue by olegchorny** [apache/incubator-pinot#5423]
https://docs.pinot.apache.org/basics/getting-started/kubernetes-quickstart
Step: 5.4 Load Demo data source
```
kubectl exec -it pod/superset-0 -n pinot-quickstart -- bash -c 'superset import_dashboards -p /etc/superset/pinot_example_dashboard.json'
...
ERROR:superset.cli:'is_restricted' is an invalid keyword argument for SqlMetric
```
It seems like to fix the issue we simply need to delete the `"is_restricted": false,` string from the `/etc/superset/pinot_example_dashboard.json` file.

**Comment by fx19880617** [comment]
Seems that we upgraded the docker version but not updated the scripts, will update it soon!
Thanks for reporting!

**Comment by fx19880617** [comment]
Updated in PR #5425
