### ISSUE TITLE
Clear results from Pinot Data Explorer

### ISSUE THREAD

**Issue by npawar** [apache/incubator-pinot#5450]
Request from @kishred 
In the Pinot Data Explorer, it is hard to tell if the new query ran and gave results. There are buttons for Copy, Excel, CSV. Can we have another button to Clear old results?

**Comment by kishoreg** [comment]
instead of a clear button, we can automatically clear every time we click on run (do this before making a call to Pinot)

**Comment by kishoreg** [comment]
This is fixed in the new query console
