### ISSUE TITLE
Remove LinkedIn config from pom

### ISSUE THREAD

**Issue by haibow** [apache/incubator-pinot#5485]
In #5190, LinkedIn deployment configs were added to the pom file. This caused Apache release to fail, and I had to remove the following lines:

https://github.com/apache/incubator-pinot/blob/ed26e8589fe5f91d2876d417aebf23575010cc76/pom.xml#L100-L106

We should try to remove LinkedIn specific configs from the repo. One alternative solution is to configure distributionManagement in command line: 
https://stackoverflow.com/questions/12435283/adding-a-maven-distribution-repository-on-the-command-line

Adding this task to remove the config above without breaking LinkedIn's nightly build.

**Comment by jackjlli** [comment]
@haibow Thanks for the heads up. I can work on this.
