### ISSUE TITLE
Spark-Pinot connector to read and write data from/to Pinot directly

### ISSUE THREAD

**Issue by mangrrua** [apache/incubator-pinot#5598]
Spark-Pinot connector to allow read data from Pinot in Spark directly(write support will be added)

https://github.com/mangrrua/spark-pinot-connector

### Motivation

Pinot has Spark batch ingestion job for offline processing. Spark batch ingestion waits input files(partitioned or not etc), and converts to the segment files, then push to Pinot. Simplified steps for a batch ingestion with spark;

1. Analyze data with your favorite tool like spark
2. Write output as csv, json, parquet etc to file system
3. Trigger Pinot Spark batch ingestion job that will create segment files from processed files in step 2 (job will write segment files to the pinot deep storage)
4. Wait Spark batch ingestion job result

As you can see, firstly we have to write data to the some temporary location(step 2). This is unnecessary operation if you will not use it for other purposes.

If you want to re-index your offline table(because requirements is changed continuously), you can use processed data in step2. But also you have to keep it(but the same data is stored in pinot). Then you can re-index data again. But in this situation, your output files and pinot table data should be same, you have to guarantee that. 

With spark-pinot connector, you can read data from Pinot directly, and write data to the Pinot directly(write support will be added). With this connector, you will have a lot of flexibility like that;

- Pinot -> Spark -> Pinot
- Pinot -> Spark -> Anywhere
- Anywhere -> Spark -> Pinot

You no need to hold processed csv/json/parquet files(step 2). Connector will be write data to the Pinot Deep Storage directly. You no need to trigger an additional Spark batch ingestion job to create segment files. 

You can re-index data easily. Just read from Pinot, and analyze it, and write it to the other table. 

Please, share your comments, thoughts. 

I also wrote future works about connector in the _README_ file of spark-pinot-connector repository.

**Comment by kishoreg** [comment]
@ karthikkakolu is also interested in this. Karthik, can you please add your requirements

**Comment by karthikkakolu** [comment]
UseCase :

Write data to custom datastore/stream (Cassandra, Kafka, Postgre) where I can write data in flat or relational way after some data post-processing.
This helps me in overcome some shortcoming in pinot related to pagination, joins  and prune data further.
Also it helps me further in leveraging some  datastore technologies which comes OOTB.

**Comment by longtrinhvan** [comment]
không làm mà đòi có ăn thì ăn đầu buồi, ăn cứt

**Comment by tannghia025** [comment]
có ví dụ write xuống pinot đâu nó như thiệt cay vl

**Comment by icefury71** [comment]
@mangrrua I see that the read side was done. Should we keep this ticket open to ensure the Spark writer to Pinot is also tracked ? Btw, is that something you're already working on ?
