### ISSUE TITLE
Support Queries Like non-aggregation group by 

### ISSUE THREAD

**Issue by fx19880617** [apache/incubator-pinot#5663]
1. select columns with GroupBy
`SELECT A FROM myTable GROUP BY A;`
Above query is equivalent to `SELECT DISTINCT A FROM myTable;`.
Do we support `DISTINCT A,B` ?

2. select transform functions with GroupBy.
`SELECT A+B FROM myTable GROUP BY A, B;`

@siddharthteotia @kishoreg

**Comment by Jackie-Jiang** [comment]
1. We support `DISTINCT` on arbitrary expressions, but `GROUP-BY` is not supported (distinct with group-by is equivalent to adding group-by into the distinct list)
2. Second query is equivalent to `SELECT DISTINCT A+B, A, B FROM myTable`

**Comment by fx19880617** [comment]
Sounds good, so we just need to handle the query rewrite I guess?

**Comment by siddharthteotia** [comment]
DISTINCT should not be combined with GROUP BY IMO. DISTINCT is a logical equivalent of a GROUP BY aggregation query without any aggregations. So, doing `SELECT DISTINCT A, B FROM Foo GROUP BY A, B` doesn't look like an intuitive query. 

So, if the user issues the query `SELECT A, B from Foo GROUP BY A, B` we should simply replace the select list with DISTINCT and remove GROUP BY

**Comment by fx19880617** [comment]
> DISTINCT should not be combined with GROUP BY IMO. DISTINCT is a logical equivalent of a GROUP BY aggregation query without any aggregations. So, doing `SELECT DISTINCT A, B FROM Foo GROUP BY A, B` doesn't look like an intuitive query.
> 
> So, if the user issues the query `SELECT A, B from Foo GROUP BY A, B` we should simply replace the select list with DISTINCT and remove GROUP BY

Yes, this is the rewrite I want to do from query compilation side.
