### ISSUE TITLE
TEXT_MATCH support for dictionary encoded columns

### ISSUE THREAD

**Issue by pradeepgv42** [apache/incubator-pinot#5666]
Currently based on documentation TEXT_MATCH only supports columns encoded as RAW, 
Need support for TEXT_MATCH on dictionary encoded columns too, to avoid converting 
dictionary encoded columns to RAW.

**Comment by siddharthteotia** [comment]
I can add it.

**Comment by Jackie-Jiang** [comment]
We should also consider supporting standalone text index (without forward index). This could potentially save a lot of spaces.

**Comment by siddharthteotia** [comment]
@pradeepgv42 , I have merged the support for text index on dictionary encoded columns. Please give it a try and let me know if you face any issues. Thanks

**Comment by siddharthteotia** [comment]
PR https://github.com/apache/incubator-pinot/pull/5667

**Comment by pradeepgv42** [comment]
Thanks a lot, will give it a try and let you know
