### ISSUE TITLE
Disallow dot in table name and column name.

### ISSUE THREAD

**Issue by fx19880617** [apache/incubator-pinot#5716]
By further support of queries involving multiple tables, we should try to prevent users creating table/schema with dot in the table name and column name.

Then we can  distinguish [database].[table_name] in FROM clause and [table_name].[column_name] for identifiers.

Current proposal is to 
1. prevent users from creating table/schemas with dot. 
2. adding a table config to allow the support for accepting the identifier format of [table].[column], this could be default to false for table created in previous pinot version but true for new created tables.
3. adding a tooling for user to turn on this in table config.

**Comment by fx19880617** [comment]
cc @KKcorps , @kishoreg , @Jackie-Jiang

**Comment by KKcorps** [comment]
This will also help in supporting integration with various UI tools which query using format - [table].[column] AS [alias]

**Comment by fx19880617** [comment]
cc  @mayankshriv
