### ISSUE TITLE
Pinot UI expandable leftmost column(Page Links)

### ISSUE THREAD

**Issue by fx19880617** [apache/incubator-pinot#5721]
Just realize we have a new UI!

![image](https://user-images.githubusercontent.com/1202120/87976060-542c4200-ca81-11ea-9edc-7710af64c5bc.png)

Regarding the new UI change, can we make the left column expandable so I can hide it. Or shall we think of making the page links on the top bar, since we already have `HOME` page there?

**Comment by shahsank3t** [comment]
We already have breadcrumbs at the top bar so it's gonna be best to add a expand/collapse button on the sidebar. I'll work on it.

**Comment by fx19880617** [comment]
> We already have breadcrumbs at the top bar so it's gonna be best to add a expand/collapse button on the sidebar. I'll work on it.

Many Thanks!

**Comment by shahsank3t** [comment]
@fx19880617 - Raised a PR https://github.com/apache/incubator-pinot/pull/5723 and also attached the images for the reference.

**Comment by shahsank3t** [comment]
@fx19880617 - this issue can be closed as the fix has already landed in.

**Comment by fx19880617** [comment]
Thanks! @shahsank3t
