### ISSUE TITLE
Controllers do not have a `/health` resource

### ISSUE THREAD

**Issue by lgo** [apache/incubator-pinot#5803]
Controllers do not have a healthcheck resource at `/health`, which is inconsistent with servers and brokers which do have an explicit `/health` resource for doing healthchecks. I believe including that would be nice for all nodes to have that for consistency on setups.

**Comment by fx19880617** [comment]
Make sense, we will add `/health` to controller.
Current health check for controller is using `/pinot-controller/admin`
