### ISSUE TITLE
Make at least pinot-admin.sh work with BusyBox (/bin/sh)

### ISSUE THREAD

**Issue by adriancole** [apache/incubator-pinot#5809]
Particularly in Docker, we're a bit better off when we can use a limited shell like BusyBox to perform commands instead of relying on bash. For example, this allows either Alpine or Distroless+BusyBox to be used.

Right now, if you try to use `pinot-admin.sh` with BusyBox (as /bin/sh), it fails for what's likely a resolvable thing.

```
./bin/pinot-admin.sh: line 32: syntax error: unexpected word (expecting ")")
```

you can see that using distroless + busybox with little modifications otherwise shaves a significant amount off the image size:

```bash
$ docker images |grep pinot
pinot                                     test                e1c4f1f12d71        5 minutes ago       339MB
apachepinot/pinot                         0.4.0               8c4112171ff7        7 weeks ago         661MB
```

```Dockerfile 
FROM apachepinot/pinot:0.4.0 as pinot

FROM openzipkin/jre-full:14.0.2-14.29.23

ENV PINOT_HOME=/opt/pinot

VOLUME ["${PINOT_HOME}/configs", "${PINOT_HOME}/data"]

COPY --from=pinot ${PINOT_HOME} ${PINOT_HOME}

# expose ports for controller/broker/server/admin
EXPOSE 9000 8099 8098 8097 8096 9514

WORKDIR ${PINOT_HOME}

ENTRYPOINT ["/bin/sh", "./bin/pinot-admin.sh"]

CMD ["run"]
```

**Comment by adriancole** [comment]
ps don't get too distracted about the JRE 14 the issue is in the shell script not the JRE, and 1.8 is even smaller ex basing on openzipkin/jre-full:1.8.0_252

```
pinot                                     test                9d7aabf0de28        33 seconds ago      244MB
```

**Comment by fx19880617** [comment]
Current Pinot image is based on image: `openjdk:8-jdk-slim` ( https://github.com/apache/incubator-pinot/blob/master/docker/images/pinot/Dockerfile#L62)

`pinot-admin.sh` is a bash script generated from the template: https://github.com/apache/incubator-pinot/blob/master/pinot-tools/src/main/resources/appAssemblerScriptTemplate

**Comment by adriancole** [comment]
https://github.com/apache/incubator-pinot/pull/5818

If you want a smaller image also, we can do that in another change. This just makes a smaller one possible. I tested it locally.
