### ISSUE TITLE
Aggregation Functions on Multi-value Columns

### ISSUE THREAD

**Issue by fx19880617** [apache/incubator-pinot#582]
Need support for distinctCount on a multi-value column.
Also might be good to rewrite the count(multi_value_column) logic to return the total elements instead of total rows.

Right now seeing query failed for:
SELECT   distinctCount(DivWheelsOns)  FROM airlineStats group by DestCityName;

{
    "traceInfo": {},
    "numDocsScanned": 0,
    "timeUsedMs": 33,
    "segmentStatistics": [],
    "exceptions": [
    {
        "message": "java.lang.UnsupportedOperationException: Reading a batch of values is not supported for multi-value BlockValSet\n\tat com.linkedin.pinot.core.operator.docvalsets.MultiValueSet.readIntValues(MultiValueSet.java:47)\n\tat com.linkedin.pinot.core.common.DataFetcher.fetchSingleDictIds(DataFetcher.java:106)\n\tat com.linkedin.pinot.core.operator.aggregation.SingleValueBlockCache.getDictIdArrayForColumn(SingleValueBlockCache.java:91)\n\tat com.linkedin.pinot.core.operator.aggregation.SingleValueBlockCache.getDoubleValueArrayForColumn(SingleValueBlockCache.java:110)\n\tat com.linkedin.pinot.core.operator.aggregation.groupby.DefaultGroupByExecutor.aggregateColumn(DefaultGroupByExecutor.java:182)\n\tat com.linkedin.pinot.core.operator.aggregation.groupby.DefaultGroupByExecutor.process(DefaultGroupByExecutor.java:133)\n\tat com.linkedin.pinot.core.operator.aggregation.groupby.AggregationGroupByOperator.processBlock(AggregationGroupByOperator.java:129)\n\tat com.linkedin.pinot.core.operator.aggregation.groupby.AggregationGroupByOperator.getNextBlock(AggregationGroupByOperator.java:98)\n\tat com.linkedin.pinot.core.operator.aggregation.groupby.AggregationGroupByOperator.getNextBlock(AggregationGroupByOperator.java:80)\n\tat com.linkedin.pinot.core.operator.BaseOperator.nextBlock(BaseOperator.java:36)\n\tat com.linkedin.pinot.core.operator.MCombineGroupByOperator$1.runJob(MCombineGroupByOperator.java:175)\n\tat com.linkedin.pinot.core.util.trace.TraceRunnable.run(TraceRunnable.java:53)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)\n\tat java.lang.Thread.run(Thread.java:745)\n",
        "errorCode": 200
    }],
    "totalDocs": 0
}

**Comment by kishoreg** [comment]
@atumbde can we fall back to reading one row at a time for multi-valued column?

**Comment by antumbde** [comment]
It should rather support reading batch of values for MultiColumns. Reading
one at a time will be slow.
We should clearly establish the semantics for multi-valued columns here.
Currently, these are treated like collapsed set of rows, which matches most
of the use-cases, but different from traditional dmbs. We should maintain
consistency for all operators going forward.

Are there any use-cases where we need proper array types ?

**Comment by kishoreg** [comment]
+1 on the batch api for multivalue as well. But I don't see an easy way to know the total number of multi-values to read upfront given a set of doc ids. For example - if we are reading 5k rows at a time and a maximum number of multi-values per row is 2k then, we will have to create the data structure to hold 5k * 2k entries upfront. Optimal way would be to for the multi-value reader to return as many entries as possible at a time and we call this in a loop until we read all values corresponding to the 5k rows. This will require changes to mv reader interface.

**Comment by antumbde** [comment]
One way is, for readers to length encode two dimensional arrays into a
single dimensional array. Callers can then pass in the pre-sized array to
read. A single call may not read all the values so there has to be a loop
as you mentioned. This approach is more memory efficient (length encoding
overhead will likely to be less) and it also limits the size of the memory
buffers we use.

(Suggested encoding is just something from top of my head. There may be
more efficient approaches)

Using ByteBuffers, we can encapsulate this in a class to make it more
transparent but arrays are more efficient than ByteBuffers.

**Comment by fx19880617** [comment]
Close as this is already supported
