### ISSUE TITLE
Pinot Query Console loosing Long granularity in results.

### ISSUE THREAD

**Issue by mr-agrwal** [apache/incubator-pinot#5829]
I am querying a table using the Pinot Query Console with id = 21400000008726127. 
The response returns with id = 21400000008726130. 
The same if I do through a broker, it is working fine.
Also, the broker is printing the query correctly in both cases.

**Comment by kishoreg** [comment]
whats the query, can you share the screen shots?

**Comment by mr-agrwal** [comment]
Query is `select * from table where id = 21400000008726127 limit 10`

**Comment by kishoreg** [comment]
@mr-agrwal is this still an issue?

**Comment by mr-agrwal** [comment]
@kishoreg Closing this, as this is an issue with javascript parsing long values. This is further discussed in detail in https://www.techempower.com/blog/2016/07/05/mangling-json-numbers/

**Comment by Jackie-Jiang** [comment]
Reopen this issue as we should show long values correctly in Pinot Query Console

**Comment by joshigaurava** [comment]
I believe there are a couple of ways to tackle this.

**1.** Given that long precision is lost when UI requests query result and that the result is display-only (meaning it is not further used in any business logic or for any processing) the server can simply send all the data as string values. However, this will require changes in the server as well as minor changes in the UI. In case the data is required to be used for some processing, it can be converted into appropriate type using `columnDataTypes` - which is when we will run into this issue, again. (Please correct me in case I am wrong, given some gaps in my Pinot UI domain knowledge.)

**2.** We can limit the changes to the UI. One solution I can think of is using json-bigint or similar library that supports converting large long values to JavaScript BigInt type and thus retain precision. This will require disabling native JSON parsing in axios with `transformResponse` and use the chosen JSON parsing library instead.

@shahsank3t

**Comment by mayankshriv** [comment]
If we go route1, then we might want to measure overhead with a large
response. I have seen orders of magnitude difference in latency seen by the
broker vs something on top of the broker (eg query console, python script,
etc) which end up doing these kinds of transformations per value.

Cheers,
Mayank

**Comment by Jackie-Jiang** [comment]
For approach 1, my concern is more about changing the format in the json response, which might break the service parsing it. But approach 1 seems the better solution because if we only change our UI to handle it, other clients reading the result can also run into the same issue.

For approach 1, there are 2 options:
1. Return all values as string (with double quotes)
2. Only convert large values to string

IMO, option 1 has consistent format of the result (always have values double quoted), but will change the format of the current results; option 2 could return some values with double quotes and some without, but won't change the format for most of the results.

Thoughts on this?

**Comment by Jackie-Jiang** [comment]
@mcvsubbu @yupeng9 @siddharthteotia @fx19880617 Do you think it could cause backward incompatible issue on client side if we return values as string as mentioned above?

**Comment by Jackie-Jiang** [comment]
Decide to go with option 2 (only convert large values to string) as it won't have any impact to most use cases (values larger than 2^53 or smaller than -2^53 are very uncommon): #6745

**Comment by Jackie-Jiang** [comment]
After more offline discussion, to prevent breaking the client code, we decide to limit the changes to the UI to handle large numbers.

**Comment by shahsank3t** [comment]
PR to fix this issue: https://github.com/apache/incubator-pinot/pull/7120
