### ISSUE TITLE
Lack of documentation on derived metric expression

### ISSUE THREAD

**Issue by ritesh-commits** [apache/incubator-pinot#5863]
Context: trying to load dashboard with /summary/autoDimensionOrder after configuring a custom metric 
- While configuring a new metric, there doesn't seem to be an option to provide derived metric expression which is required isSimpleRatioMetric. Because of this the SummaryResponse is always being computed using the runAdditiveCube algorithm.
- runAdditiveCubeAlgorithm is having hardcoded MerticAggFunction as SUM, so even if we configure another metric like AVG or COUNT, the default agg function is not being considered while constructing Bulk Requests in BaseCubePinotClient.

**Comment by kishoreg** [comment]
@suvodeep-pyne ^^
