### ISSUE TITLE
Expose response stats in Pinot java client's BrokerReponse

### ISSUE THREAD

**Issue by buchireddy** [apache/incubator-pinot#5871]
Currently, response stats like `numDocsScanned`, `totalDocs`, and `timeUsedMs` are returned in the JSON response body but they're not exposed to the client in https://github.com/apache/incubator-pinot/blob/master/pinot-clients/pinot-java-client/src/main/java/org/apache/pinot/client/BrokerResponse.java

Exposing the response stats would allow the client application to log the stats for slow queries and make the debugging easy instead of trying to reproduce the slow queries again.

I will raise a PR for this unless people have any comments.

cc @kishoreg

**Comment by kishoreg** [comment]
@buchireddy  can we close this?

**Comment by buchireddy** [comment]
Yes. The PR is merged.
