### ISSUE TITLE
The `/tables/{TABLE}/schema` controller API fails when a tablename does not match its schema name

### ISSUE THREAD

**Issue by lgo** [apache/incubator-pinot#5878]
When using schemas and tables that do not have the same name, the `/tables/{TABLE}/schema` controller API fails and indicates there's no schema available. This prevents using things like ingestion jobs because they request the schema from the controller.

**Comment by Jackie-Jiang** [comment]
@lgo FYI, we are planning to force schema to be the same name as table (without type suffix) in the future. Are there specific reasons why you want to have different names for them?

**Comment by lgo** [comment]
Makes sense!

We haven’t been using for anything that matters.

While experimenting with Pinot I’ve been setting up multiple tables with
different indexing configurations, and further duplicating those by using
multiple test datasets for any particular table. In practice, there’s no
reason these shouldn’t be separate schemas / tables.
