### ISSUE TITLE
Ensure time-column compatibility between schema and tableconfig

### ISSUE THREAD

**Issue by mcvsubbu** [apache/incubator-pinot#5915]
We need to check the following when a tableConfig is added or updated, or when a schema is updated:

The time column name (and type) in the tableConfig is the same as the primary time column name and type in the schema. The schema may not exist, in which case it is ok (we currently allow creating offline tables without a schema). The schema could be under the default (recommended) name -- the table name, or it could be under a different name indicate in the table config. The time column in the schema could either be TimeFieldSpec or DateTimeFieldSpec

Similarly, when updating (or adding) a schema, we should make sure that the same consistency checks are done. A schema may be added after an offline table is added. Or, a schema may be updated. It is possible that there is no table corresponding to a schema (yet) since the table is yet to be created (we recommend creating schema first).

The only case we will miss out is if a (offline) table is created with a different schema name, and then schema is added later. We will leave this as a corner case.

**Comment by Jackie-Jiang** [comment]
@npawar I think we can enforce the following things:
- Schema must exist for a table before adding/updating the table
- Schema name must be the same as raw table name

Then we can do cross validation when updating table config or schema. Without enforcement 2, it is hard to find the table config for a given schema
