### ISSUE TITLE
Swagger UI not working.

### ISSUE THREAD

**Issue by mr-agrwal** [apache/incubator-pinot#5937]
I am not able to access the Swagger UI. All APIs for `swaggerui-dist/lib/*` and `swaggerui-dist/css/*` are failing with 404.

<img width="1790" alt="Screenshot 2020-08-28 at 8 56 02 PM" src="https://user-images.githubusercontent.com/24796847/91584939-01438580-e971-11ea-8918-60a92b1b13e7.png">

**Comment by kishoreg** [comment]
@jackjlli looks like you change broker swagger

git checkout 87b5b77264c1f05ac6073ff77e1728667dce1e1b works

git checkout e9ad1e017bf06ac579014357462c86861a31cf7d DOES NOT WORK

**Comment by mr-agrwal** [comment]
@jackjlli @kishoreg The fix works :). Thanks!!
