### ISSUE TITLE
Partitioning mis-match can lead to bad query results in Realtime

### ISSUE THREAD

**Issue by mayankshriv** [apache/incubator-pinot#6029]
The current code simply assumes partitionId from kafka partition to be in accordance with the partition function defined in table config. In case there is a mis-match on kafka partition and what's set in table config, that leads to incorrect pruning of segments causing bad results for query.

There was indeed an old behavior were we wiped out the incorrect partition metadata when committing the segment, which would limit the scope to consuming queries. At the very minimum, we should bring back that behavior. This is important as we can run into these issues in various situations:

* Increase in number of partitions from Kafka side.
* Partition function change on either side (accidental or intentional).

**Comment by Jackie-Jiang** [comment]
Fix for the issue: #6031

**Comment by Jackie-Jiang** [comment]
Perf testing branch which removes the partition info for consuming segments: https://github.com/apache/incubator-pinot/tree/remove_consuming_partition_info

**Comment by Jackie-Jiang** [comment]
Removing the partition info for consuming segments could cause performance degradation for extremely high QPS use cases. Filed #6078 as a work-around without performance impact.
