### ISSUE TITLE
Regenerate star-tree index when the index config is changed on reloads

### ISSUE THREAD

**Issue by pradeepgv42** [apache/incubator-pinot#6092]
Currently only newer segments gets the updated star-tree index config. Reloads could regenerate star-tree index for already committeed segments too.

**Comment by kishoreg** [comment]
I thought this was already supported? @Jackie-Jiang

**Comment by Jackie-Jiang** [comment]
We don't support generating new star-tree when there is existing star-tree

**Comment by Jackie-Jiang** [comment]
Allow modifying/removing existing star-trees during segment reload: #6100
