### ISSUE TITLE
Use star-tree index when filteres not part of index match all rows of a segment

### ISSUE THREAD

**Issue by pradeepgv42** [apache/incubator-pinot#6093]
Currently all filters needed to be part of star-tree to be able to utiliize the index
for hybrid tables timestamp column gets auto added as afilter so that causes the star-tree index to be not used
if timestamp column is not part of the index already. So, potential optimization here is to utilize star-tree index if the
filters that are not part of star-tree match all the rows in a segment.

**Comment by Jackie-Jiang** [comment]
This is a little bit tricky because the filter is shared among all segments. Will try to figure out a work around

**Comment by Jackie-Jiang** [comment]
Enhance star-tree to skip matching-all predicate on non-star-tree dimension: #6109
