### ISSUE TITLE
Querying a partitioned column for a non-existent value times out

### ISSUE THREAD

**Issue by lgo** [apache/incubator-pinot#6145]
With a partition column, say `type`, if we uploaded segments containing `type=foo` but had the following query over a non-existent value:

    SELECT * FROM table WHERE type = 'bar'

The query appears to time out.

Happy to provide more configuration details if that's helpful. This table also had a lot of data, so there could have been some slow-path scan happening instead.

**Comment by Jackie-Jiang** [comment]
This is unexpected. This query should be at lease as fast as `SELECT * FROM table WHERE type = 'foo'`. Is this query always timing out? If it can return result sometimes, the stats in the response will be very helpful for debugging the issue.

**Comment by lgo** [comment]
Gathering more details from folks who had originally noticed this issue, will circle back when I have specifics. I might have mispoken about the issue since just trying what I described seems to have worked 😅.

**Comment by lgo** [comment]
Egh sorry, this was a bit of noise. I completely mixed up issues we were seeing -- instead we were seeing expected behaviour (broker pruning and immedately returning zero segments, which was initially unexpected but we later realized we had only partially uploaded data).
