### ISSUE TITLE
Cluster Manager: API for getting table state

### ISSUE THREAD

**Issue by npawar** [apache/incubator-pinot#6169]
We have an API to enable/disable table - `GET /tables/{tableName}?state={enable/disable}&type={OFFLINE/REALTIME}`. But we don't have an API which returns the table state (enabled/disabled). 
A user will not know if the table is enabled or disabled, unless they get the ideal state znode for the table (even GET idealstate doesn't return that info). An API exclusively for getting table state would be nice, especially for an application like cluster manager, which will provide an Enable/Disable button.
API can be `GET tables/{tableName}/state` and response can be "enabled" or "disabled"

**Comment by galalen** [comment]
I want to take this issue

**Comment by npawar** [comment]
Sounds good @galalen . Please ping me if you have any questions

**Comment by galalen** [comment]
@npawar  you can check my PR https://github.com/apache/incubator-pinot/pull/6211
I'm reading the state from the IdealState.
