### ISSUE TITLE
Cluster Manager: Endpoint for creating a table config and schema json, given the input fields

### ISSUE THREAD

**Issue by npawar** [apache/incubator-pinot#6170]
This is to assist the Cluster Manager UI with building the table config, without having to know about the exact json structure

**Comment by galalen** [comment]
Can you provide more information! because I guess there is an endpoint for creating a schema, and table config will be created automatically with creating the table, correct me if I'm wrong.

**Comment by npawar** [comment]
Correct. There are endpoints for both. This item was more with respect to the cluster manager. We wanted to avoid the cluster manager having to create a complex json on the UI. 
But we have managed completing the UI without making it too complicated. So this item is not relevant anymore.

Are you looking for issues to contribute to? Please ping me or @kishoreg and we can find you something :)
