### ISSUE TITLE
Fact-dim join via Lookup UDF

### ISSUE THREAD

**Issue by dharakk** [apache/incubator-pinot#6191]
This issue represents the work to support join like functionality via Lookup UDFs in Pinot.

Design document for proposed feature: https://docs.google.com/document/d/1InWmxbRqwcqIakzvoEWHLxtX4XR9H5L01256EbAUHV8/edit?usp=sharing

**Comment by siddharthteotia** [comment]
Can we use the existing issue?
https://github.com/apache/incubator-pinot/issues/5664
