### ISSUE TITLE
Supports parquet file parallel processing with LocalPinoFS

### ISSUE THREAD

**Issue by flykent1990** [apache/incubator-pinot#6206]
hi team pinot 

Can you provide me with multi parquet file processing with multi threads

I am currently processing 18Gb parquet file (152 files) with LocalPinotFS which takes 200min

Well, having added this feature will improve performance

![Screen Shot 2020-10-29 at 03 13 42](https://user-images.githubusercontent.com/71525567/97491446-c1ab1100-1994-11eb-9b75-476eb1cf23b8.png)
![Screen Shot 2020-10-28 at 00 08 09](https://user-images.githubusercontent.com/71525567/97491384-ac35e700-1994-11eb-9bff-e17083496202.png)

**Comment by fx19880617** [comment]
One way you can try is to start a local spark cluster and submit a spark job to it:
You can ref to this doc, just replace the s3 part with your local. https://docs.pinot.apache.org/users/tutorials/ingest-parquet-files-from-s3-using-spark

**Comment by flykent1990** [comment]
hi @fx19880617 

I run the spark job and get an error like this ... can you help me

command run : 
./bin/spark-submit --class org.apache.pinot.tools.admin.command.LaunchDataIngestionJobCommand --master "local[2]" --deploy-mode client --conf "spark.driver.extraClassPath="$CLASSPATH:$PLUGINS_CLASSPATH""  local:///app/pinot/lib/pinot-all-0.5.0-jar-with-dependencies.jar -jobSpecFile /tmp/structure_schema/ingestionJobSpec_begin_spark.yaml

![Screen Shot 2020-10-29 at 05 20 43](https://user-images.githubusercontent.com/71525567/97503404-89f99480-19a7-11eb-8c31-b9a12789e845.png)

**Comment by flykent1990** [comment]
ok tks @fx19880617 
using spark job I reduce processing time by 50% parquet file

**Comment by fx19880617** [comment]
> ok tks @fx19880617
> using spark job I reduce processing time by 50% parquet file

👍

**Comment by fx19880617** [comment]
https://github.com/apache/incubator-pinot/pull/6214

**Comment by fx19880617** [comment]
#6214 is merged. This standalone mode segment creation parallelism is also supported.
