### ISSUE TITLE
Support parsing of double quoted Hex strings

### ISSUE THREAD

**Issue by apucher** [apache/incubator-pinot#6230]
As a follow-up to #6228

Hi everyone,

It looks like Hex string aren't identified as such when using double quoted strings.

The query `SELECT * FROM mytable WHERE my_bytes_column = "0146"` (double quotes) returns an exception, whereas `SELECT * FROM mytable WHERE my_bytes_column = "0146"` (single quotes) works as expected.

I'm probably missing some subtleties of the specification, yet this seems a bit counter-intuitive.

Addendum - Exception:

> [
>   {
>     "errorCode": 200,
>     "message": "QueryExecutionError:\njava.lang.UnsupportedOperationException\n\tat org.apache.pinot.core.segment.index.readers.BytesDictionary.getDoubleValue(BytesDictionary.java:78)\n\tat org.apache.pinot.core.segment.index.readers.Dictionary.readDoubleValues(Dictionary.java:149)\n\tat org.apache.pinot.core.common.DataFetcher$ColumnValueReader.readDoubleValues(DataFetcher.java:401)\n\tat org.apache.pinot.core.common.DataFetcher.fetchDoubleValues(DataFetcher.java:134)\n\tat org.apache.pinot.core.common.DataBlockCache.getDoubleValuesForSVColumn(DataBlockCache.java:175)\n\tat org.apache.pinot.core.operator.docvalsets.ProjectionBlockValSet.getDoubleValuesSV(ProjectionBlockValSet.java:89)\n\tat org.apache.pinot.core.operator.transform.function.IdentifierTransformFunction.transformToDoubleValuesSV(IdentifierTransformFunction.java:94)\n\tat org.apache.pinot.core.operator.transform.function.SubtractionTransformFunction.transformToDoubleValuesSV(SubtractionTransformFunction.java:89)\n\tat org.apache.pinot.core.operator.dociditerators.ExpressionScanDocIdIterator.processProjectionBlock(ExpressionScanDocIdIterator.java:159)\n\tat org.apache.pinot.core.operator.dociditerators.ExpressionScanDocIdIterator.next(ExpressionScanDocIdIterator.java:81)\n\tat org.apache.pinot.core.operator.DocIdSetOperator.getNextBlock(DocIdSetOperator.java:69)\n\tat org.apache.pinot.core.operator.DocIdSetOperator.getNextBlock(DocIdSetOperator.java:35)\n\tat org.apache.pinot.core.operator.BaseOperator.nextBlock(BaseOperator.java:49)\n\tat org.apache.pinot.core.operator.ProjectionOperator.getNextBlock(ProjectionOperator.java:57)"
>   }
> ]

**Comment by Jackie-Jiang** [comment]
@apucher Double quote in SQL means identifier instead of literal, only single quote means literal. Double quote can be used to skip special characters in the identifier, e.g. `"member-id"`

**Comment by apucher** [comment]
ok, should we close this one then? @fx19880617

**Comment by fx19880617** [comment]
yes 👍
