### ISSUE TITLE
[Pinot]Support environment variables injection in Table Spec

### ISSUE THREAD

**Issue by Aka-shi** [apache/incubator-pinot#6232]
For streaming ingestion from Kafka, we might have to provide ssl configs if Kafka is using SSL protocol for communication. As of now the property values have to be passed transparently in the table spec. 

It would be safer and better to support environment variables in table spec, so that ssl truststore and keystore passwords can be set as environment variables in the container and then reference them in the table spec.

**Comment by Aka-shi** [comment]
@fx19880617 @kishoreg

**Comment by fx19880617** [comment]
Close as PR merged in https://github.com/apache/incubator-pinot/pull/6271
