### ISSUE TITLE
pinot cluster on docker unable to restore imported data after docker restarts

### ISSUE THREAD

**Issue by rec7y33** [apache/incubator-pinot#6257]
Hello, I followed this guide : https://docs.pinot.apache.org/basics/getting-started/advanced-pinot-setup
and have successfully setup the cluster in docker on my ubuntu VM.
However, once I restart the docker service/ reboot the ubuntu VM, i found out broker log has this error: 
`No server found for request 8: select * from sitevisitordata limit 10`

please advice. thanks

**Comment by fx19880617** [comment]
if you are running in docker, then you can set this config in pinot server conf file:
```
pinot.server.netty.host=pinot-server-0
```
This `pinot-server-0` is the docker container name, so when we start the docker container, we need to specify the `--name `
e.g.
```
docker run --rm -ti \
    --name pinot-server-0 \
    --network=pinot-demo \
    --mount type=bind,source=/tmp/pinot-docker-conf,target=/tmp \
    apachepinot/pinot:latest StartServer \
    -zkAddress zookeeper:2181 -clusterName pinot-docker \
    -configFileName /tmp/server.conf
```

**Comment by rec7y33** [comment]
@fx19880617 Thanks. But where can I find the config files, or do I need to make them myself?

**Comment by fx19880617** [comment]
> @fx19880617 Thanks. But where can I find the config files, or do I need to make them myself?

yes, you can follow this wiki(https://docs.pinot.apache.org/users/tutorials/use-s3-and-pinot-in-docker) to create a sample conf file, note that the wiki doesn't request a conf file for pinot-broker, but you need a one-line conf file to start pinot broker.

**Comment by rec7y33** [comment]
thanks :)
