### ISSUE TITLE
code":500,"error":"org.apache.pinot.plugin.stream.kafka20.KafkaConsumerFactory

### ISSUE THREAD

**Issue by himanshudas** [apache/incubator-pinot#6280]
I am getting an error on running this docker command. Request help.

Command:
```
docker run --network=pinot-demo --name pinot-streaming-table-creation apachepinot/pinot:latest AddTable -schemaFile examples/stream/githubEvents/pullRequestMergedEvents_schema.json -tableConfigFile examples/stream/githubEvents/docker/pullRequestMergedEvents_realtime_table_config.json -controllerHost pinot-controller -controllerPort 9000 -exec
```
Output:
```
Executing command: AddTable -tableConfigFile examples/stream/githubEvents/docker/pullRequestMergedEvents_realtime_table_config.json -schemaFile examples/stream/githubEvents/pullRequestMergedEvents_schema.json -controllerHost pinot-controller -controllerPort 9000 -exec
```
Error:

```Sending request: http://pinot-controller:9000/schemas to controller: c0e845ca03ba, version: Unknown
{"code":500,"error":"org.apache.pinot.plugin.stream.kafka20.KafkaConsumerFactory"}```

**Comment by fx19880617** [comment]
This means that your pinot controller is not started with the Kafka20 plugin. Can you show me how you deploy the pinot controller?

**Comment by himanshudas** [comment]
Hello @fx19880617 ,

Thanks a lot for your response. I have followed the steps from this tutorial: https://docs.pinot.apache.org/getting-started/recipes/github-events-stream

I have following container running currently:

<img width="1518" alt="Screenshot 2020-11-19 at 2 17 50 PM" src="https://user-images.githubusercontent.com/1238723/99642888-085ec900-2a72-11eb-83e0-fe9d276ae930.png">

I think I already have kafka20 in the config: 

<img width="1150" alt="Screenshot 2020-11-19 at 2 32 08 PM" src="https://user-images.githubusercontent.com/1238723/99644740-4f4dbe00-2a74-11eb-922a-810334731928.png">


Kindly, help on what I am missing?

**Comment by fx19880617** [comment]
> Hello @fx19880617 ,
> 
> Thanks a lot for your response. I have followed the steps from this tutorial: https://docs.pinot.apache.org/getting-started/recipes/github-events-stream
> 
> I have following container running currently:
> 
> <img alt="Screenshot 2020-11-19 at 2 17 50 PM" width="1518" src="https://user-images.githubusercontent.com/1238723/99642888-085ec900-2a72-11eb-83e0-fe9d276ae930.png">
> 
> I think I already have kafka20 in the config:
> 
> <img alt="Screenshot 2020-11-19 at 2 32 08 PM" width="1150" src="https://user-images.githubusercontent.com/1238723/99644740-4f4dbe00-2a74-11eb-922a-810334731928.png">
> 
> Kindly, help on what I am missing?

Got it. There was a bug in the Advanced Setup doc(https://docs.pinot.apache.org/basics/getting-started/advanced-pinot-setup#2-start-pinot-controller). It's missing `-Dplugins.dir=/opt/pinot/plugins` in the `JAVA_OPTS` variable to let Pinot Controller start up while loading all the plugins.

I've updated the tutorial to start Pinot Controller/Broker/Server.

Could you give it a try?

**Comment by himanshudas** [comment]
Hello @fx19880617 ,

Thanks a lot for your help. The setup worked for me after following above step.

I am closing this issue now.
