### ISSUE TITLE
Pluggable metrics registry

### ISSUE THREAD

**Issue by fx19880617** [apache/incubator-pinot#6282]
The current codebase uses old yammer libs, and the world already moves to dropwizard.

Considering the difficulty of the upgrade for existing users, shall we think of abstract Metrics/MetricsRegistry(maybe more) as interfaces and build yammer/dropwizard plugins for that?

**Comment by fx19880617** [comment]
@jackjlli ^^

**Comment by chenboat** [comment]
+1 for this. We have seen a lot of issues with the out dated yammer metrics lib. For example, it has the stale metrics issue as reported here: https://engineering.salesforce.com/be-careful-with-reservoirs-708884018daf. This makes some alerts not working properly. The new lib should allow configuration of more recent metrics implementation. @fx19880617 @Jackie-Jiang

**Comment by daniellavoie** [comment]
What do you people think of https://micrometer.io/ ?

**Comment by chenboat** [comment]
micrometer.io looks a good idea if it can deliver like slf4j.

**Comment by icefury71** [comment]
Looks like work has already begun on this : https://github.com/apache/incubator-pinot/pull/6579 thanks to @jackjlli
