### ISSUE TITLE
[Controller UI] show cluster name 

### ISSUE THREAD

**Issue by fx19880617** [apache/incubator-pinot#6337]
Can we add cluster info on the front page of controller UI.

There is an API on controller for this : `/cluster/info`. It currently shows only the cluster name.

![image](https://user-images.githubusercontent.com/1202120/101545882-c59b5d00-395c-11eb-90d8-1ee06e67a7d0.png)

**Comment by shahsank3t** [comment]
@fx19880617 - Pull request to address this change: https://github.com/apache/incubator-pinot/pull/6338
