### ISSUE TITLE
Old Segments not expired or deleted - Text Index + Inverted Index

### ISSUE THREAD

**Issue by pabrahamusa** [apache/incubator-pinot#6351]
I am using Text Index and Inverted Index as well , noticed that the segment retention is not working. Pinot is not expiring or deleting the old segments . My segments config

`  "segmentsConfig": {
        "timeColumnName": "five_mins_epoch",
        "timeType": "MINUTES",
        "retentionTimeUnit": "DAYS",
        "retentionTimeValue": "3",
        "schemaName": "myschema",
        "replication": "1",
        "replicasPerPartition": "1",
        "segmentPushType": "APPEND",
        "completionConfig": {
           "completionMode": "DOWNLOAD"
        }
      },`

As per the config segments older than 3 days should be expired and get deleted from the disk. However this is not happening and I have to manually delete the segments which is a big overhead in housekeeping.

**Comment by pabrahamusa** [comment]
Could someone please share some document about how the retention works, I want to make sure I am implementing it properly

**Comment by kishoreg** [comment]
@pabrahamusa the retention manager deletes the segment by looking at the data time in the segment, not the creation time. Please look at the segment metadata in pinot UI and see if the max timestamp in the segment is older than 3 days.

@npawar please correct me if I am wrong here.

**Comment by pabrahamusa** [comment]
Thanks @kishoreg , today I noticed there are lot of tmp- segments created and a huge tmp file also. And all the active segments are updated with current date. Not sure what is happening however some sort of archiving process I assume. However even for retention 3 days I can still see active segments that is 5 days old.

**Comment by pabrahamusa** [comment]
one of the old but active segment testlog__0__0__20201208T0619Z
4:19
{
  "segment.realtime.endOffset": "100000",
  "segment.start.time": "96444486000000000",
  "segment.time.unit": "MILLISECONDS",
  "segment.flush.threshold.size": "100000",
  "segment.realtime.startOffset": "0",
  "segment.end.time": "96444522000000000",
  "segment.total.docs": "100000",
  "segment.table.name": "testlog_REALTIME",
  "segment.realtime.numReplicas": "1",
  "segment.creation.time": "1607408391025",
  "segment.realtime.download.url": "http://test-pinot-controller-1.test-pinot-controller-headless.logging.svc.cluster.local:9000/segments/testlog/testlog__0__0__20201208T0619Z",
  "segment.name": "testlog__0__0__20201208T0619Z",
  "segment.index.version": "v3",
  "segment.flush.threshold.time": null,
  "segment.type": "REALTIME",
  "segment.crc": "2336961740",
  "segment.realtime.status": "DONE"
}

**Comment by npawar** [comment]
Hi @pabrahamusa as Kishore mentioned, `retention manager deletes the segment by looking at the data time in the segment, not the creation time`. Data start/end time is the  `segment.start.time` and `segment.end.time`. In the metadata you shared, these 2 fields appear to have invalid values `96444522000000000`. That could be the reason the retention manager is not picking the segment.

**Comment by pabrahamusa** [comment]
@npawar What is controlling the end time for a segment?  My segment config is as follows. The segment timeType is in MINUTES and I am passing five_mins_epoch in MILLISECONDS . Something like 1607472900000 (Wed Dec 09 2020 00:15:00) . So entire 5 minutes the five_mins_epoch is same for all the records. Do you see any issue here which can affect segment endtime? 

`
      "segmentsConfig": {
        "timeColumnName": "five_mins_epoch",
        "timeType": "MINUTES",
        "retentionTimeUnit": "DAYS",
        "retentionTimeValue": "3",
        "schemaName": "myschema",
        "replication": "1",
        "replicasPerPartition": "1",
        "segmentPushType": "APPEND",
        "completionConfig": {
           "completionMode": "DOWNLOAD"
        }
      }
`

**Comment by npawar** [comment]
> @npawar What is controlling the end time for a segment? My segment config is as follows. The segment timeType is in MINUTES and I am passing five_mins_epoch in MILLISECONDS . Something like 1607472900000 (Wed Dec 09 2020 00:15:00) . So entire 5 minutes the five_mins_epoch is same for all the records. Do you see any issue here which can affect segment endtime?
> 
> `"segmentsConfig": { "timeColumnName": "five_mins_epoch", "timeType": "MINUTES", "retentionTimeUnit": "DAYS", "retentionTimeValue": "3", "schemaName": "myschema", "replication": "1", "replicasPerPartition": "1", "segmentPushType": "APPEND", "completionConfig": { "completionMode": "DOWNLOAD" } }`

The timeType should be MILLISECONDS. But I suspect the problem is in the schema. Could you paste the Pinot schema here?

**Comment by pabrahamusa** [comment]
@npawar , Here is the full schema

{
  "REALTIME": {
    "tableName": "test_REALTIME",
    "tableType": "REALTIME",
    "segmentsConfig": {
      "timeType": "MINUTES",
      "schemaName": "test",
      "timeColumnName": "five_mins_epoch",
      "retentionTimeUnit": "DAYS",
      "retentionTimeValue": "3",
      "replication": "1",
      "segmentPushType": "APPEND",
      "replicasPerPartition": "1",
      "completionConfig": {
        "completionMode": "DOWNLOAD"
      }
    },
    "tenants": {
      "broker": "DefaultTenant",
      "server": "DefaultTenant"
    },
    "tableIndexConfig": {
      "aggregateMetrics": false,
      "nullHandlingEnabled": false,
      "sortedColumn": [
        "timemillis"
      ],
      "enableDefaultStarTree": false,
      "enableDynamicStarTreeCreation": false,
      "loadMode": "MMAP",
      "invertedIndexColumns": [
        "timemillis",
        "cname",
        "nname",
        "pname",
        "host",
        "cluster"
      ],
      "autoGeneratedInvertedIndex": false,
      "createInvertedIndexDuringSegmentGeneration": false,
      "streamConfigs": {
        "streamType": "kafka",
        "stream.kafka.consumer.type": "simple",
        "stream.kafka.topic.name": "test_all_logs",
        "stream.kafka.decoder.class.name": "org.apache.pinot.plugin.stream.kafka.KafkaJSONMessageDecoder",
        "stream.kafka.consumer.factory.class.name": "org.apache.pinot.plugin.stream.kafka20.KafkaConsumerFactory",
        "stream.kafka.zk.broker.url": "cp-zookeeper-headless.logging.svc.cluster.local:2181",
        "stream.kafka.broker.list": "cp-kafka-headless.logging.svc.cluster.local:9092",
        "realtime.segment.flush.threshold.time": "12h",
        "realtime.segment.flush.threshold.size": "100000",
        "stream.kafka.consumer.prop.auto.offset.reset": "smallest"
      }
    },
    "metadata": {
      "customConfigs": {}
    },
    "fieldConfigList": [
      {
        "name": "log",
        "encodingType": "RAW",
        "indexType": "TEXT",
        "properties": {
          "enableQueryCacheForTextIndex": "false",
          "deriveNumDocsPerChunkForRawIndex": "true"
        }
      },
      {
        "name": "cname",
        "encodingType": "RAW",
        "indexType": "TEXT",
        "properties": {
          "enableQueryCacheForTextIndex": "false",
          "deriveNumDocsPerChunkForRawIndex": "true"
        }
      },
      {
        "name": "pname",
        "encodingType": "RAW",
        "indexType": "TEXT",
        "properties": {
          "enableQueryCacheForTextIndex": "false",
          "deriveNumDocsPerChunkForRawIndex": "true"
        }
      },
      {
        "name": "nname",
        "encodingType": "RAW",
        "indexType": "TEXT",
        "properties": {
          "enableQueryCacheForTextIndex": "false",
          "deriveNumDocsPerChunkForRawIndex": "true"
        }
      },
      {
        "name": "host",
        "encodingType": "RAW",
        "indexType": "TEXT",
        "properties": {
          "enableQueryCacheForTextIndex": "false",
          "deriveNumDocsPerChunkForRawIndex": "true"
        }
      },
      {
        "name": "cluster",
        "encodingType": "RAW",
        "indexType": "TEXT",
        "properties": {
          "enableQueryCacheForTextIndex": "false",
          "deriveNumDocsPerChunkForRawIndex": "true"
        }
      }
    ],
    "ingestionConfig": {}
  }
}

**Comment by npawar** [comment]
This one's the table config. Schema can be found under `GET /schemas/test` or under Schema tab in Swagger

**Comment by pabrahamusa** [comment]
@npawar Thanks , Please see the Schema

{
  "schemaName": "test",
  "dimensionFieldSpecs": [
    {
      "name": "log",
      "dataType": "STRING",
      "maxLength": 10000,
      "defaultNullValue": ""
    },
    {
      "name": "cluster",
      "dataType": "STRING",
      "defaultNullValue": ""
    },
    {
      "name": "cname",
      "dataType": "STRING",
      "defaultNullValue": ""
    },
    {
      "name": "nname",
      "dataType": "STRING",
      "defaultNullValue": ""
    },
    {
      "name": "pname",
      "dataType": "STRING",
      "defaultNullValue": ""
    },
    {
      "name": "host",
      "dataType": "STRING",
      "defaultNullValue": ""
    },
    {
      "name": "timemillis",
      "dataType": "LONG",
      "defaultNullValue": 100000
    }
  ],
  "timeFieldSpec": {
    "incomingGranularitySpec": {
      "name": "five_mins_epoch",
      "dataType": "LONG",
      "timeType": "MINUTES"
    }
  }
}

**Comment by npawar** [comment]
Based on the example value you provided (1607472900000 ), the time column in your schema should be MILLISECONDS.
Something like this:
```
"dateTimeFieldSpecs": [
    {
      "name": "five_mins_epoch",
      "dataType": "LONG",
      "format": "1:MILLISECONDS:EPOCH",
      "granularity": "5:MINUTES"
    }
]
```
Also, we've moved onto the "dateTimeFieldSpec" for defining time columns. Example: https://docs.pinot.apache.org/basics/components/schema#creating-a-schema

**Comment by pabrahamusa** [comment]
Thanks @npawar I updated my schema to dateTimeFieldSpecs, will check and update the metadata on new segment .

**Comment by kishoreg** [comment]
@pabrahamusa were you able to resolve this?

**Comment by pabrahamusa** [comment]
@kishoreg I will check the segments status and update shortly

**Comment by pabrahamusa** [comment]
@kishoreg I checked and can see the segments with correct end-date are getting deleted as per the retention period.  Thanks for the help here. Also if in case I have to update the metadata is it possible via rest api call?

**Comment by pabrahamusa** [comment]
Thanks this is working fine after the change mentioned above. Thanks @npawar and @kishoreg for your help
