### ISSUE TITLE
Deletion of segments not working properly

### ISSUE THREAD

**Issue by mr-agrwal** [apache/incubator-pinot#6436]
When Uploading segments to controller using Segment Uri Push, It is putting the segments in path
`fake_job_for_testing_time_based_OFFLINE/fake_job_for_testing_time_based_OFFLINE_18597_18597_0`
whereas when trying to delete the segments, it is calling exists on path
`fake_job_for_testing_time_based/fake_job_for_testing_time_based_OFFLINE_18597_18597_0`
which logs
`Failed to find local segment file for segment`

**Comment by fx19880617** [comment]
Fixed in #6445
