### ISSUE TITLE
Query Pinot through MyBatis

### ISSUE THREAD

**Issue by HyunjoonCho** [apache/incubator-pinot#6444]
Hello,

I'm trying to access Pinot through Spring-MyBatis but having some trouble. 
Came up with workaround for several steps, but having hard time redirecting execute() to executeQuery().
While MyBatis Handler calls method execute() of prepared statement, Pinot only uses method executeQuery(); 
execute(), execute(sql) and other calls throw exception.
https://github.com/mybatis/mybatis-3/blob/master/src/main/java/org/apache/ibatis/executor/statement/PreparedStatementHandler.java#L64 

I'm curious about the reason behind this behavior of pinot prepared statement. 
Intentionally blocked those access due to limited functionality of current jdbc client? 
And any suggestion on workaround would be appreciated - tried to wrap prepared statement, connection and driver, but found out that constructor of PinotConnection is not public.

Thanks

**Comment by fx19880617** [comment]
@KKcorps 
Have you tried the pinot-jdbc-client?
https://github.com/apache/incubator-pinot/tree/master/pinot-clients/pinot-jdbc-client
https://mvnrepository.com/artifact/org.apache.pinot/pinot-jdbc-client

**Comment by HyunjoonCho** [comment]
Thanks for your comment, 
yes I just solved it using jdbc client :)
