### ISSUE TITLE
Handle creation of empty segment

### ISSUE THREAD

**Issue by npawar** [apache/incubator-pinot#6453]
Currently, if segment creation is started with no rows, we error out. We stumbled upon this issue while working on the Kinesis connector. In the Kinesis connector, we are going to trigger segment completion on criteria of reaching  end-of-shard (in addition to rows and time thresholds). It is possible that the CONSUMING segment associated with the shard has no rows, and then the segment completion is reached.
It would be good if we could make Pinot gracefully handle segment creation with 0 rows.

**Comment by mcvsubbu** [comment]
I am not sure creating empty segments is a good idea all the time. Certainly, for offline use cases, it is better to flag this early and fail the job, so at the minimum, we should implement this as an option.

Even in the realtime use cases, generating many empty segments may cause unnecessary overhead during query processing.

**Comment by npawar** [comment]
Regarding `Even in the realtime use cases, generating many empty segments may cause unnecessary overhead during query processing.` - In realtime case especially, this will be a very very rare occurrence. It will never even happen in streams which only rely on time/rows thresholds.
And whatever empty segments we do end up with, they should be handled in the segment merge/replace.

Also, lets keep the behavior consistent across offline/realtime. Especially considering we have a feature to filter rows during ingestion, it is possible that in offline, we cross the check for empty segment, but then fail later anyway because everything got filtered out.

FYI @kishoreg @Jackie-Jiang

**Comment by Jackie-Jiang** [comment]
Please make sure the metadata can be correctly generated without any record. Also, we should prune out empty segments as the first step to prevent the query engine (both Broker and Server side) throwing exception while processing them. Currently we assume the segment cannot be empty.

**Comment by npawar** [comment]
do you mean we introduce a broker side pruner, something like EmptySegmentPruner, that is always in effect? Or did you mean prune it in some other way?

**Comment by Jackie-Jiang** [comment]
Yes, and we need to make sure all the pruners on the broker side can handle the empty segment metadata properly

**Comment by jackjlli** [comment]
Hi, what's the pros and cons between creating an empty segment v.s. not creating a segment, e.g. in Kinesis connector?

Failing the segment creation could be helpful to early detect the issue from the upstream. If we release this constraint, issues may appear underneath the creation job without any notice.

In realtime side, there could be no streaming data for newly created tables, thus it'd lead to empty segments flushed in the table.
