### ISSUE TITLE
`helm upgrade` command fails

### ISSUE THREAD

**Issue by pv93** [apache/incubator-pinot#6454]
`helm version` output:

```
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"dirty", GoVersion:"go1.15.5"}
```

Upgrading from chart version 0.2.2 to 0.2.3

Ran the following command:
```
helm upgrade -i pinot pinot/pinot -n pinot --reuse-values -f helm.yaml
```

Got output:
```
Error: UPGRADE FAILED: template: pinot/templates/minion/statefulset.yml:23:11: executing "pinot/templates/minion/statefulset.yml" at <include "pinot.minion.fullname" .>: error calling include: template: no template "pinot.minion.fullname" associated with template "gotpl"
```
Looks like this has to do with the latest upgrade to the chart: addition of the minion https://github.com/apache/incubator-pinot/pull/6430

**Comment by fx19880617** [comment]
Thanks for reporting this! The issue is that `_helpers.tpl` is not packaged correctly. 

Updated the package in PR #6459.
