### ISSUE TITLE
Make minion workers stateless

### ISSUE THREAD

**Issue by daniellavoie** [apache/incubator-pinot#6526]
While minion workers are stateless by nature, the task framework requires them to register with a specific `instance_id`  to Helix. Minion workers tends to be scaled up and down based fluctuant workload requirements. While it does not prevent the system from worker, scaled down instances will remain as DEAD in the cluster manager.

If Pinot includes a cleanup job for minion instances, then we could update the Helm chart to move the minion pods from a statefulset to a stateless deployment.

**Comment by fx19880617** [comment]
#6543 Pinot code change on cleaning up dead minion instances from helix.
K8s changes will follow once this PR is checked in.
