### ISSUE TITLE
Zookeeper client version so zookeeper client will re-resolve hosts when IP has changed

### ISSUE THREAD

**Issue by dongxiaoman** [apache/incubator-pinot#6554]
We have the same situation as mentioned in [Zookeeper bug here](https://issues.apache.org/jira/browse/ZOOKEEPER-2184) . Simple version is, we will replace zookeeper servers with a new host that has new IP address, but still keep the host name in the DNS.
This bug in Zookeeper client is fixed in `3.4.13`+ or 3.5.5+, or 3.6.0+ and pinot is using 3.4.11
Can we upgrade at least the minor version to 3.4.13?

**Comment by fx19880617** [comment]
I'm seeing an issue of zk client connection for jdk14+ after the upgrade.
Will investigate this.
