### ISSUE TITLE
add execute() to JDBC PinotPreparedStatement

### ISSUE THREAD

**Issue by gracewalkuski** [apache/incubator-pinot#6557]
Add the implementation for the `execute()` function in the [PinotPreparedStatement](https://github.com/apache/incubator-pinot/blob/release-0.6.0/pinot-clients/pinot-jdbc-client/src/main/java/org/apache/pinot/client/PinotPreparedStatement.java) class. 

Override the following function [here](https://github.com/apache/incubator-pinot/blob/e892cb2942f1f41ac7056d977eeca0e5b22897d0/pinot-clients/pinot-jdbc-client/src/main/java/org/apache/pinot/client/base/AbstractBasePreparedStatement.java#L97)
```
  @Override
  public boolean execute()
      throws SQLException {
    throw new UnsupportedOperationException();
  }
```

This will allow for apps using the JDBC to use the `execute()` function without any special configuration to call executeQuery() instead. Currently, it calls the execute function [here](https://github.com/apache/incubator-pinot/blob/e892cb2942f1f41ac7056d977eeca0e5b22897d0/pinot-clients/pinot-jdbc-client/src/main/java/org/apache/pinot/client/base/AbstractBasePreparedStatement.java#L97) which caused a lot of confusion initially. 

Specifically, this allows [Jooq](https://www.jooq.org/) to call Pinot correctly with its `.fetch()` method.

**Comment by fx19880617** [comment]
@KKcorps ^^

**Comment by KKcorps** [comment]
Taking it up.

**Comment by KKcorps** [comment]
@gracewalkuski can you check if the code in the PR is what you are looking for or something more is needed.

**Comment by gracewalkuski** [comment]
Thanks @KKcorps ! I'll test it locally and let you know.

**Comment by gracewalkuski** [comment]
Yes that does work! Thanks so much!

**Comment by fx19880617** [comment]
Thanks for adding this support @KKcorps !
Thanks for raising the issue and testing the patch @gracewalkuski !
