### ISSUE TITLE
Remove Travis CI in Pinot repo

### ISSUE THREAD

**Issue by jackjlli** [apache/incubator-pinot#6615]
Travis CI is quite unstable and its resource is strictly limited, which takes much longer to finish comparing to Github Actions. And since Travis CI is mainly used for LinkedIn to publish internal release, as this pipeline has been migrated to Github Actions internally, Travis CI can be dropped in Pinot public repo.

This issue is used to track the status of dropping Travis CI in Pinot repo.

**Comment by fx19880617** [comment]
+1000000!
