### ISSUE TITLE
RealtimeTableDataManager shuts down SegmentBuildTimeLeaseExtender for all tables in the host

### ISSUE THREAD

**Issue by mcvsubbu** [apache/incubator-pinot#6671]
This bug has surfaced because of recent commit PR #6608 . The problem is that the lease extender is a common one for all tables, and we cannot shut it down until the system is being shut down. 
@Jackie-Jiang

**Comment by mcvsubbu** [comment]
There are other issues with the lease extender as well, as pointed out by @Jackie-Jiang . Looks like things changed during controller distribution and the lease extender was not fixed right.
Overall, here is what needs to happen:
- Lease extended should get instantiated in HelixServerStarter instead of table data manager. It should also get stopped there. It should be instantiated without a table name , of course.
- The addSegment API of lease extender should be called with an addition argument of protocol handler , so that the extend lease request goes to the right controller for the table.

**Comment by mcvsubbu** [comment]
Looks like leases have not been working right since PR #4323 on multi-tenant realtime clusters. no effect on single-tenant clusters.

**Comment by mcvsubbu** [comment]
cc: @snleee , @sajjad-moradi

**Comment by snleee** [comment]
1. The routing back to the proper leader controller has been happening. `ServerSegmentCompletionProtocolHandler:createSegmentCompletionUrl()`.
2. The main issue was that the server-side only had the lease extender per instance id, which means that 1 single global lease extender.
3. @jtao15's fix changes servers to have lease extender per table. I think that this is cleaner than having one global lease extender. (1-1 mapping for lease extender - data manager for a table).

@mcvsubbu How do you think? Can you also review the above PR?

**Comment by mcvsubbu** [comment]
@snleee  The existing implementation may not route to the correct controller in multi-tenant use cases. If you notice, the constructor of lease extender takes a table name, and that table name is used to find the controller to talk to.

**Comment by snleee** [comment]
@mcvsubbu You're right. I got confused. It keeps using the same lease extender since it looks up based on the instanceId
