### ISSUE TITLE
Wrong port to start a standalone Superset deployment

### ISSUE THREAD

**Issue by lzwaan** [apache/incubator-pinot#6753]
Port should be -p 8088:8088 not like below:

docker run \
  --network pinot-demo \
  --name=superset \
  -p 8088:8080 \
  -d apachepinot/pinot-superset:latest

**Comment by fx19880617** [comment]
right, superset is on port 8088. This  should be 8088:8088

**Comment by fx19880617** [comment]
I've updated the doc here: https://app.gitbook.com/@apache-pinot/s/apache-pinot-cookbook/integrations/superset
