### ISSUE TITLE
Support IN predicate in ColumnValue SegmentPruner

### ISSUE THREAD

**Issue by GSharayu** [apache/incubator-pinot#6756]
Server side segment pruning is currently supported for =, RANGE filter operators using min-max value stats (segment metadata). Similarly, bloom filter is also used for = filter. 

For IN filter operator, we should add support for min-max value based pruning if the number of values in the IN clause are below a certain threshold. 

Adding this support for large number of values in IN clause won't be helpful as the pruning may not happen (since values are likely to be spread across several segments) and the time to prune itself may negate the benefits. So, let's start with a configurable value with default being less than 10.

**Comment by siddharthteotia** [comment]
Support added in PR - https://github.com/apache/incubator-pinot/pull/6776
