### ISSUE TITLE
Schema not updated when selecting another table in Query Console Tab on Pinot UI

### ISSUE THREAD

**Issue by MrNeocore** [apache/incubator-pinot#6805]
Copied from Slack

## Context:
- I've got 2 tables with 2 separate schemas
- I'm on the Query Console Tab

## Problem :
- I click on  a table, the schema appears below it - the schema is valid (the one corresponding to this table)
- I then click on the other table, the schema of the previous table remains
- If I reload the page and click on the other table first, its schema remains after I click on the other table

## Info:
- The schemas really are different
- Actually the API calls when inspecting the page return the correct schemas
- So it seems it only is a UI-related issue
- Force reloading Firefox page (ignore cache) doesn't solve the issue 
- Version is `0.7.0-SNAPSHOT-621ceb021cefa1640708f3bb4d576270717f70d6`

https://user-images.githubusercontent.com/22521284/115054939-21648c80-9ee1-11eb-92b5-4e24e72f7ae7.mp4

**Comment by shahsank3t** [comment]
Thanks for reporting @MrNeocore I am able to reproduce this and working on a fix for it.

**Comment by shahsank3t** [comment]
Fixed and created a PR - https://github.com/apache/incubator-pinot/pull/6806
