### ISSUE TITLE
UI - Not showing all pinot servers in Tenant details

### ISSUE THREAD

**Issue by mangrrua** [apache/incubator-pinot#6821]
I have 2 pinot servers, and 1 tenant called as `DefaultTenant`. In the tenant section of the UI, seems DefaultTenant has only 1 server. When i want to see details for the DefaultTenant, both of two servers seems, but only one server shown as **link**. But when i check the `/tenants/{tenantName}/metadata` endpoint for DefaultTenant; two servers are listed for this tenant. Seems there is a bug in the UI.

@fx19880617

**Comment by xiangfu0** [comment]
Thanks for reporting this! 
Pasted the page:
![image](https://user-images.githubusercontent.com/1202120/115625404-e1225700-a2b0-11eb-9a46-db60e595d7cd.png)


cc @shahsank3t

**Comment by shahsank3t** [comment]
@mangrrua @xiangfu0 
Fixed this issue in https://github.com/apache/incubator-pinot/pull/6934
