### ISSUE TITLE
Support selection of duplicate columns

### ISSUE THREAD

**Issue by snleee** [apache/incubator-pinot#6844]
Currently, Pinot does the deduplication when the query has multiple selection clauses on the same column. The standard SQL doesn't perform the deduplication in this case.

```
select colA as xx, colA as yy from T

--> this returns `colA` and `as clause` is ignored
```

**Comment by Jackie-Jiang** [comment]
Does standard SQL support making 2 different alias on the same column?
To support selecting duplicate columns, you can change `SelectionDataTableReducer` and pass `selectionColumns` into `SelectionOperatorUtils.renderResultTableWithoutOrdering()`

**Comment by snleee** [comment]
@Jackie-Jiang Thank you for the suggestion. I will take a look on that.
