### ISSUE TITLE
controller UI crashes if no brokers or servers online

### ISSUE THREAD

**Issue by apucher** [apache/incubator-pinot#6896]
The controller UI crashes ungracefully to a white screen if all brokers are offline and/or all servers are offline.

<img width="1792" alt="Screen Shot 2021-05-08 at 11 52 46 PM" src="https://user-images.githubusercontent.com/25439965/117563140-bed25c80-b058-11eb-9828-2e5c2fa86597.png">

**Comment by shahsank3t** [comment]
@apucher 
Fixed this issue in PR: https://github.com/apache/incubator-pinot/pull/6935
