### ISSUE TITLE
Fix the handling of time and date time columns in rule engine

### ISSUE THREAD

**Issue by GSharayu** [apache/incubator-pinot#6937]
Fix the handling of time and date time columns and remove corresponding limitations	

FlagQueryRule - Flags queries with tables that have time column (deprecated) or one or more DateTime columns (new way of specifying time columns) but don't use it in queries in the filter clause as a feedback to the user that they should consider using the time column as a filter. Two things need to be fixed in this rule

- Should also consider DateTime columns in addition to the Time column
- Fix a bug - if the schema of the table doesn't have a time/datetime column(s), it is stored as null and thus flags queries even for the tables that don't have such columns in the schema because it checks the presence of null in the set of filter columns. 
This will also require some cleanup in InputManager.

There are some other restrictions in the rule engine around the use of time/datetime column that we can relax. 

The function isPrimaryDateTime(String col) checks if the provided column is the time column. Let's rename this to more meaningful - something like isTimeOrDateTimeColumn(String col)

Now we can fix the usage of this function in BloomFilterRule and InvertedSortedIndex recommendation rules. 

Our initial implementation of these rules somehow assumed that typically time/datetime columns will always be used in range predicates thus precluding the use of inverted/sorted index and bloom filters on such columns because such structures only help with =, IN filter operators. Thus the implementation of these rules outright ignore the time/datetime column from the recommendation upfront. However, users may have =/IN queries on time/datetime column and so might benefit from inverted/sorted/bloom. So, let's remove this restriction from the rules.

**Comment by siddharthteotia** [comment]
Closed by PR - https://github.com/apache/incubator-pinot/pull/6938
