### ISSUE TITLE
Stream Quickstart 0.7.1 fails with SSL Handshake failed error

### ISSUE THREAD

**Issue by MacNale** [apache/incubator-pinot#6943]
`docker run     --network=pinot-demo     --name pinot-quickstart     -p 9000:9000     -d apachepinot/pinot:test QuickStart     -type stream`
![image](https://user-images.githubusercontent.com/14235758/118851979-f1215c80-b897-11eb-931e-2cba81f15249.png)

I tried to run locally, same error.

I could launch 0.6.1 successfully with docker.

**Comment by mayankshriv** [comment]
From the log it seems to use 0.8.0 and not 0.7.1 (which is working for us).

**Comment by mayankshriv** [comment]
Tried `pinot-tools/target/pinot-tools-pkg/bin/quick-start-streaming.sh` with latest master and could not reproduce the issue. Are you on VPN @MacNale that might be causing this?

**Comment by apucher** [comment]
this looks like a ssl-handshake issue with the meetup provider. not related to pinot internals

**Comment by xiangfu0** [comment]
have you tried with `quick-start-hybrid.sh` and if that one works?
Also, check if you can run the below command directly:
```
websocat wss://stream.meetup.com/2/rsvps
```

**Comment by MacNale** [comment]
Disconnected from VPN and ran the command from my mac. It worked fine. This seems to be a problem with downloading the stream from meetup.com.
