### ISSUE TITLE
Pinot ui can't show all the pinot servers

### ISSUE THREAD

**Issue by cxing** [apache/incubator-pinot#6948]
We have 30 server clusters but this ui just show 10
![image](https://user-images.githubusercontent.com/13634486/118905765-f392bd80-b94e-11eb-997b-539ae5f2a51e.png)

**Comment by xiangfu0** [comment]
@shahsank3t

**Comment by shahsank3t** [comment]
@cxing @xiangfu0 
PR raised: https://github.com/apache/incubator-pinot/pull/6956
