### ISSUE TITLE
Implement PassThroughTransformOperator to optimize select queries

### ISSUE THREAD

**Issue by GSharayu** [apache/incubator-pinot#6972]
For general select queries

e.g SELECT * FROM Foo  ..... LIMIT N

e.g SELECT col1, col2  ..... FROM Foo  .... LIMIT N

the columns are identifier expressions and not some transform functions. So, we should have a PassThroughTransformOperator that avoids the if conditional check repeatedly in TransformBlock. 

If the columns selected in the query are identifier expressions then no need to make the check again and again for every block fetch of 10K records. Since during query planning time, we have the information available in TransformPlanNode if selected expressions are identifiers or not, we can make an optimization to have a specialized TransformOperator and TransformBlock that simply does a pass through and avoids the repeated if check at query runtime. 

This is something that would have been done in pinot if there was run time query specific code generation. Since we currently don't have it, we can handwrite the specialized operator.

**Comment by siddharthteotia** [comment]
Resolved by PR https://github.com/apache/incubator-pinot/pull/6973
