### ISSUE TITLE
Support range index rule recommendation 

### ISSUE THREAD

**Issue by GSharayu** [apache/incubator-pinot#7034]
Currently, 

As part of pinot automated onboarding, we support automated inverted index and sorted index recommendations.
Wiki Doc: https://cwiki.apache.org/confluence/display/PINOT/Automated+Inverted+Index+Recommendation+for+Pinot

 This issue will add an automated support to recommend range index in pinot.

**Comment by siddharthteotia** [comment]
Support added in PR https://github.com/apache/incubator-pinot/pull/7063
