### ISSUE TITLE
The column with JSON index on shall not be truncated

### ISSUE THREAD

**Issue by yupeng9** [apache/incubator-pinot#7051]
The column of string type of a default length, and value beyond the threshold will be truncated. This creates issue for JSON field (i.e. with JSON index on), as the JSON parsing will fail. We shall have a validation rule that requires overriding the length (perhaps to the max) for such fields.

**Comment by Jackie-Jiang** [comment]
You may set the json field as data type `JSON` (introduced in #6878) and the value won't be truncated

**Comment by yupeng9** [comment]
Good to know that. A `JSON` type is useful

**Comment by kishoreg** [comment]
do we have docs updated?

**Comment by Jackie-Jiang** [comment]
Yes, the doc is updated here: https://docs.pinot.apache.org/basics/components/schema
