### ISSUE TITLE
Remove unapproved company Icon from apache pinot website

### ISSUE THREAD

**Issue by pabrahamasurion** [apache/incubator-pinot#7143]
Hello,

I can see Asurion logo listed in Apache Pinot Website.  As per corporate policy this is not allowed until there is an approval. I did not provided any approval to anyone as well. Could you guys please remove Asurion logo from https://pinot.apache.org/ 

Thanks

**Comment by xiangfu0** [comment]
Thanks for bringing this up. Removed the logo!
