### ISSUE TITLE
About refreshing table after schema changed

### ISSUE THREAD

**Issue by cenyuhai** [apache/incubator-pinot#74]
When we alter the schema, we need to restart the pinot server, but we have many tables in one server, if one table changes,  all the tables in this server are affected.   Can you provider a method to refresh one table?

**Comment by Jackie-Jiang** [comment]
You may use the reload API: **{controllerHost:port}/tables/{tableName}/segments/{segmentName}/reload** for single segment reload or **{controllerHost:port}/tables/{tableName}/segments/reload** for whole table reload.
