### ISSUE TITLE
Why performance of pinot is not good!

### ISSUE THREAD

**Issue by alan2018** [apache/incubator-pinot#77]
The Data:
  I used the suite of TPC-H tools suite of tools to generate a dataset,with a target size of 1GB.
   tablename :lineitem

test SQL:
   SELECT SUM(L_EXTENDEDPRICE),SUM(L_DISCOUNT),SUM(L_TAX)  FROM lineitem where  L_RECEIPTDATE <= 915120000 and L_RECEIPTDATE >=694195200;
915120000:  1999/1/1 0:0:0
694195200:   1992/1/1 0:0:0

Result:
Pinot time: about 8s
Druid time:about 0.8s

Do you have TPC-H test Data?

**Comment by kishoreg** [comment]
We don't generate index on any column by default. Can you upload the data set you generated.

**Comment by alan2018** [comment]
You can get data from the address:http://static.druid.io/data/benchmarks/tpch/1/lineitem.tbl.gz
How to generate index on column?

**Comment by giaosudau** [comment]
@kishoreg how to turn on all columns will be indexed by default?.

**Comment by kishoreg** [comment]
we dont do that by default. In most cases having  index on all columns results is not needed  but I agree having a feature  that can generate index on all columns by default can be helpful. Let me create an issue.
