### ISSUE TITLE
Server directly pull data from hdfs/s3

### ISSUE THREAD

**Issue by fx19880617** [apache/incubator-pinot#81]
Hi team,
Current controller design always requires people to push data from hdfs to controller NFS and then server can download data from controller. But actually if there is no firewall between server and hadoop/s3, then server should be able to pull segments from hdfs/s3 directly. 

My thought is for pushing segment job, we can just upload a metadata json(combination of segment meta, creation meta, hdfs/s3 path, etc) for the segment instead of the whole segment.

For server side, server will check the data source and download the segment from either controller or hdfs or s3.

**Comment by kishoreg** [comment]
does this mean we will not allow posting payload along with the push call. What do you think about supporting both? Ability to send segment data or a url to download it from.

**Comment by fx19880617** [comment]
Should be push to controller always, just use different protocol in http header. One is real segment, another is metadata only.

**Comment by dhaval2025** [comment]
We should do this .. only thing is that we will have to handle auth ... without punching in the the secrets in the config...
